dmtcp/dmtcp

src/plugin/ipc/file/fileconnection.cpp

This patch is a workaround for what is arguably a bug in the Luster
FS. See: https://jira.hpdd.intel.com/browse/LU-6528.  When multiple
independent processes call mkdir() on an existing directory,
a process can sometimes get an EACCES error, which causes our
createDirectoryStructure function to assert. This patch adds an
extra check (using the stat() call) in createDirectoryStructure in
case the call to mkdir() returned EACCES.

fileconnection: add check to verify the existence of a dir

---

src/signalwrappers.cpp
src/uniquepid.cpp
src/uniquepid.h
src/writeckpt.cpp

Fix for signal wrappers.

---

src/threadlist.cpp

In glibc >= 2.21, sem_wait registers a cleanup handler before blocking
for the semaphore. The handler is popped before returning from it.
However, if we use it in stopthisthread(), the cleanup handler is not
popped up on restart because, we do a longjmp. Thus if a thread, that was
created before ckpt, were to do pthread_exit, the pthread_exit routine
will pop all pending cleanup handlers and try to execute them. At this
point the stale sem_wait() handler results in SEGFAULT (since the
semaphore is invalid now).
This was most noticeable on pthread2/3 tests since they have threads that
are created before ckpt and removed after restart.
Here is the glibc commit: https://sourceware.org/git/?p=glibc.git;a=commit;h=042e1521c794a945edc43b5bfa7e69ad70420524

Fixes #45: Bug fix for sem_wait and glibc >= 2.21.

---

src/mtcp/mtcp_restart.c

For shared memory areas backed by unlinked files, MTCP used to create
the file with RW permissions and populate it with the contents from the
ckpt image. Next, it would close and reopen the file descriptor to
reflect the appropriate pre-ckpt flags. Finally, the memory area would
be mapped and the file would be unlinked.
When there are two or more processes involved, they all follow the same
steps. However, sometimes, one of the processes will unlink the file
right when a different process is in the middle of closing and reopening
the file descriptor. This would cause the reopening of the file to fail
and the process to exit.
The fix is to remove the closing/reopening logic since the flags on the
file descriptors don't matter. We are anyways creating the shared-memory
area with appropriate …

MTCP: Fixed a race w/ unlinked shared-memory files.

---

include/dmtcp.h
src/dmtcpplugin.cpp
src/util_misc.cpp

@gc00, @karya0: I decided to take a stab at fixing `dmtcp_get_restart_env()`. This is my best guess of what the original code in the function was doing. :-)

Fixes issue #149

---

src/dmtcp_launch.cpp

We have a long-standing bug for DMTCP with --gzip under aarch64.  Until we find the time to look at it carefully, we should automatically turn off --gzip.  This patch does that for aarch64..

Aarch64 no gzip

---

src/mtcp/mtcp_restart.c

This patch fixes an issue reported by Ankit. The problem was that We
were hitting an mtcp_abort() in adjust_for_smaller_file_size() because
MTCP was failing to restore a memory region where the application had
mmap-ed /dev/zero, probably to emulate a fast calloc().
The original intent of the function was to figure out if the backing
file of an mmap-ed region has truncated since checkpoint time, compute
the difference, and then patch the memory region using MAP_ANONYMOUS.
The logic in the function is difficult to follow, but, more importantly,
it fails to correctly handle the situation when the size of the backing
file of an mmap-ed region is 0, which is the case with /dev/zero.
This patch simplifies the code and fixes this issue by: a) mmap-ing an
entire region as MAP_ANONYMOUS if its …

mtcp_restart: fix the logic for mmap-ing truncated files

---

src/plugin/Makefile.am
src/plugin/Makefile.in
src/plugin/pid/pid_syscallsreal.c
src/plugin/pid/pidwrappers.cpp
src/plugin/pid/pidwrappers.h
src/plugin/pid/sched_wrappers.cpp
test/autotest.py
test/sched_test.c

pid-plugin: Add wrappers for sched_* functions

---

include/dmtcp.h
src/dmtcpplugin.cpp

dmtcp.h: Fix documentation of two *_get_status functions

---

src/mtcpinterface.cpp
src/mtcpinterface.h

Minor cleanup of code.  (4 lines of code to review:  cleanup suggested by issue #216)

Change isRestart from int to bool in C++ files

---

src/dmtcp_coordinator.cpp
src/plugin/ipc/event/eventwrappers.cpp
src/plugin/ipc/event/eventwrappers.h
src/writeckpt.cpp
test/autotest.py

Added a wrapper for `__poll_chk` libc call.
Fixes #241.

Fix for script test.

---

src/dmtcpplugin.cpp

Increase the max. buffer size to 12kB

fixup! modify-env: Increase max. supported file size to 12kB

---

Makefile.in

Tiny change in top level Makefile.in; Should be easy to review

Cleaner display of glibc version in Makefile.in

---

Makefile.in
configure
doc/multi-arch.txt
plugin/Makefile.am
plugin/Makefile.in
src/Makefile.am
src/Makefile.in
src/plugin/Makefile.am
src/plugin/Makefile.in
test/Makefile.in

The steps listed in doc/multi-arch.txt should work now.

Fixed multi-architecture support.

---

Makefile.in
configure.ac
jalib/jalloc.cpp
src/Makefile.am
src/coordinatorapi.cpp
src/dmtcpplugin.cpp
src/plugin/ipc/socket/socketwrappers.cpp
src/plugin/pid/pidwrappers.h
src/plugin/timer/timerlist.h
src/plugin/timer/timerwrappers.cpp
src/threadlist.cpp
test/forkexec.c
test/inotify1.c
test/pthread4.c

This should be an easy review:  a bunch of isolated cases of polishing.

Minor polishing of comments and code

---

src/dmtcp_coordinator.cpp

Currently, `dmtcp_coordinator --exit-after-ckpt` causes the processes of the current computation to all be killed immediately after the first checkpoint.  It is similar to  `dmtcp_coordinator --exit-on-last`, except that `--exit-on-last` causes the coordinator to exit when the last peer process exits.
The bug is that after a checkpoint, the coordinator correctly kills all peer processes, and then the coordinator turns off the `--exit-after-ckpt` feature.  The help message implies that the `--exit-after-ckpt` feature is persistent, and if a new computation starts on this coordinator, the new computation should also be killed after the checkpoint.  But instead, the feature is turned off after the first checkpoint.
The original code is by @karya0, and dates from May, 2013.  Maybe this is old …

dmtcp_coordinator: fix --exit-after-ckpt

---

contrib/infiniband/ibv_internal.h
contrib/infiniband/ibvctx.c

If one verb function is called by another internally, the real resources should be used, instead of the shadowed structures.

IB: added detection of nested verbs call.

---

src/coordinatorapi.cpp
src/dmtcpplugin.cpp
src/processinfo.cpp
src/processinfo.h

Fix for dmtcp_checkpoint()

---

src/threadwrappers.cpp
test/pthread4.c

Fix threadwrappers.cpp

---

test/plugin/applic-delayed-ckpt/Makefile

Remove stray `echo "DEBUGGING"` in` test/plugin/applic-delayed-ckpt`

Remove old "DEBUGGING" stmt

---

src/threadwrappers.cpp

I accidentally pushed in my changes and closed PR #316.

fixup! threadwrappers: Fix segfault when clone call fails

---

src/dmtcp_restart.cpp

@gc00 @ankitcse07 
Ankit, this fixes your case. Please, verify.

Fix restart case where all root procs are orphaned.

---

src/dmtcp_restart.cpp

Fix restart case where all independent roots of process trees are

---

src/constants.h
src/coordinatorapi.cpp
src/dmtcp_coordinator.cpp
src/dmtcp_coordinator.h
src/dmtcpworker.cpp
src/execwrappers.cpp
src/plugin/ipc/ssh/dmtcp_ssh.cpp
src/plugin/ipc/ssh/dmtcp_sshd.cpp
src/plugin/ipc/ssh/ssh.cpp
src/plugin/ipc/ssh/ssh.h
src/restartscript.cpp
src/restartscript.h

This PR is created for #296 to merge this in 2.5 branch. @karya0 has already marked it ship it tag. So committing in 2.5 branch now

Rsh support in 2.5 branch 

---

src/coordinatorapi.cpp
src/coordinatorapi.h
src/dmtcp_command.cpp
src/dmtcp_coordinator.cpp
src/dmtcp_coordinator.h

Add dmtcp_command option to print list of connected workers

---

src/dmtcp_restart.cpp

Remove print in restart

---

configure
configure.ac
src/mtcp/mtcp_restart.c

Could someone give me a fast review for this one?  It's a trivial change in strings (comments) only.  The intent is obvious.
(I am hoping to get --fast-restart working again soon.)

Fast restart not working

---

src/writeckpt.cpp

Current strategy is to skip pages storing in checkpoint database
which are not anonymous and don't have any READ/WRITE permissions.
Anonymous area is identified reading /proc/<pid>/maps file with empty
string for the name. Adding only anonymous pages was necessary to checkpoint
database as user might have removed the permissions temporarily and
may later restore the permissions for later use. In case restore
of permissions happens after restart and in case we have skipped mapping
these pages to user memory then it will result in segvs if in user code.
Assumption that only anonymous areas have this property is breaking
on some kernels.
In my case if memory is allocated on heap and mprotect gives it PROT_NONE
permission then I see different behavior on SUSE12 and RHEL6 machines.
1) On …

Creating PR to merge in 3.0.0 branch for #414 Closed PR 

---

src/dmtcpplugin.cpp

dmtcp_get_restart_env: Increase MAXSIZE to 120KB

---

contrib/delayresume/Makefile.in
contrib/delayresume/README
contrib/delayresume/delayresume.cpp
contrib/delayresume/delayresume.h
contrib/delayresume/test/dmtcp-delayed-resume-test.c

The README file describes the plugin, usage, and use-case.

delayresume: Add new plugin

---

plugin/batch-queue/discover_slurm.cpp
plugin/modify-env/modify-env.c
src/coordinatorapi.cpp
src/dlsym_default.c
src/dmtcp_coordinator.cpp
src/dmtcpplugin.cpp
src/execwrappers.cpp
src/mtcp/mtcp_restart.c
src/plugin/ipc/event/eventconnection.cpp
src/plugin/ipc/file/fileconnection.cpp
src/plugin/ipc/ssh/dmtcp_ssh.cpp
src/plugin/ipc/ssh/ssh.cpp
src/plugin/pid/pid_miscwrappers.cpp
src/restartscript.cpp
src/signalwrappers.cpp
src/threadlist.cpp
src/util_exec.cpp
src/writeckpt.cpp

The issues and the fixes should be obvious in most places. In places where the code's intent wasn't clear to me, I have added comments.

Fix misc. issues pointed out by static analysis v3

---

src/mtcp/mtcp_restart.c

This patch fixes issue #342. I have tested this with ICC-16.0.3.
There were two issues:
- Missing definition for the memfence() function; and
- Incorrect offset for the restorememoryareas_fptr in the rinfo
struct.
The second bug was introduced in the commit: dec2c26 when new fields
were added to the rinfo struct.

Fix mtcp_restart for Intel C compiler

---

src/coordinatorapi.cpp
src/coordinatorapi.h
src/dmtcp_launch.cpp
src/dmtcp_restart.cpp
src/util_exec.cpp

A few more fixes:
- Fix a case of use-after-free in `getCoordHostAndPort()`
- Fix a case of use of incorrect function for freeing up resources (allocated by `popen()`)

fixup! Fix misc. issues pointed out by static analysis

---

src/util_init.cpp

This is a duplicate of PR #460 (which was pushed into master/3.0)

Comment JLOG call, fails with --enable-debug (for version 2.5.0)

---

src/plugin/pid/pid_filewrappers.cpp
src/plugin/pid/pid_syscallsreal.c
src/plugin/pid/pidwrappers.h

pid-plugin: Fix pid virtualization for /proc

---

plugin/batch-queue/job_examples/stampede/README
plugin/batch-queue/job_examples/stampede/slurm_launch.job
plugin/batch-queue/job_examples/stampede/slurm_rstr.job

Added job scripts for Stampede.

---

jalib/jfilesystem.cpp

Change static object to static object pointer.

---

src/constants.h
src/coordinatorapi.cpp
src/dmtcp_coordinator.cpp
src/dmtcp_coordinator.h
src/dmtcpworker.cpp
src/execwrappers.cpp
src/plugin/ipc/ssh/dmtcp_ssh.cpp
src/plugin/ipc/ssh/dmtcp_sshd.cpp
src/plugin/ipc/ssh/ssh.cpp
src/plugin/ipc/ssh/ssh.h
src/restartscript.cpp
src/restartscript.h

This is a port of PR #296 to master (DMTCP-3.0).

Support for rsh in DMTCP-3.0

---

jalib/jalloc.cpp

This PR is cherry-picked from the PR #484 of @karya0 that was already pushed into branches 2.5 and 2.4.7.

Minor Jalloc fixes (for 3.0)

---

src/plugin/ipc/file/fileconnlist.cpp

Better fix of warning in commit 5387d89 from PR #521

Minor fix of warning: improvement on 5387d89

---

contrib/infiniband/ibvctx.c

IB: minor fix of blocking call wrappers.

---

src/plugin/ipc/ssh/dmtcp_sshd.cpp

This PR fixes the SSH functionality broken by #478.

Fixed SSH support.

---

src/threadlist.cpp

The signal handlers must be restored before the restart hooks for
plugins are called because some plugins might perform tasks that could
potentially generate a signal. For example, the timer plugin may restore
a timer which will fire right away, and not having an appropriate signal
handler could kill the process.

Fixed a bug in signal handler restoration during restart.

---

src/miscwrappers.cpp
src/syscallsreal.c
src/syscallwrappers.h

These wrappers were left over from FReD changes from few years ago.

Removed stale pthread_cond_* wrappers.

---

src/mtcp/Makefile.debug
src/mtcp/mtcp_util.h
src/mtcp/restore_libc.h

This was leftover from cf53732.

Renamed DEBUG to LOGGING in mtcp.

---

contrib/infiniband/ibvctx.c

Seems that merge conflict was not solved properly. Compilation fails at this step.

Fix obvious error

---

src/plugin/ipc/file/fileconnection.cpp

Fixed a corner case where path and cwd are equal.

---

src/restartscript.cpp

restart_script: Fix a bug introduced in 9a02dab4

---

src/mtcp/restore_libc.c

Enhances 2be93da0af12ca496b3118db8d815ff796be7965

Fixed tls_pid_offset for newer (>2.24) glibc.

---

src/dmtcp_launch.cpp
test/posix-mq2.c

Fix compilation warnings and errors with gcc 7

---

src/util_misc.cpp

This is a duplicate of PR #644 for 3.0

Added NSCD area for CentOS.

---

src/util_misc.cpp

Fix a gcc warning that was caused by PR #374.

Fix warnings in util_misc.cpp

---

test/plugin/applic-delayed-ckpt/README
test/plugin/applic-initiated-ckpt/README

Fix README of test/plugin/applic-init*-ckpt, etc.

---

src/mtcp/restore_libc.c

Fixes for glibc >=24. Enhances 250a962.

---

Makefile.in
configure
configure.ac
include/config.h.in
src/coordinatorapi.cpp
src/mtcp/restore_libc.c
src/plugin/pid/pid.cpp
src/plugin/pid/pid_syscallsreal.c
src/processinfo.cpp
src/shareddata.cpp
src/threadlist.cpp
test/dmtcp2.c
test/pthread2.c

The eight commit messages tell what are the changes.  This will be easy to review if you simply review each of the eight commits, one-by-one.
* After reviewing my commits, please do not push it in yourself, unless you are willing to take ownership of my code and be responsible for any bugs in my code.  There are several subtleties here, and I would like the privilege of reflecting on any review comments before pushing this in, rather than later committing fixes for earlier commits.
* Also, if you do decide to push this in yourself, please don't push it in as a single merge.  I know that github makes that easier to do.  But it means that 'git log' shows eight semi-unrelated commits as a single giant merge.  :-(
* WSL is not yet working.  At checkpoint time, doLocking gets stuck on fcntl …

Series of small commits, fixes motivated by WSL (Windows Subsystem for Linux)

---

src/mtcp/mtcp_restart.c

Tested with make check on aarch64.

Fixed fp restoration for aarch64.

---

src/threadlist.cpp

Hey,
minor change to fix the build in case HAS_PR_SET_PTRACER  is not available.
Best
Johannes

fixed build when HAS_PR_SET_PTRACER not available

---

src/coordinatorapi.cpp

This is a copy of PR #656 by @jiajuncao.  I'm pushing in this commit because it retains @jiajuncao as author, instead of hiding the origin via a merge.

Duplicate of PR #618 for 3.0.

---

src/mtcp/mtcp_header.h
src/mtcp/mtcp_restart.c
src/mtcp/restore_libc.c
src/mtcp/tlsutil.h

Slight re-formatting to port PR #609 from 2.6 branch to 3.0/master branch.  See PR #609 for description.

MPIFIX workaround: handle GS in per-thread storage

---

src/dmtcp_coordinator.cpp
src/pluginmanager.cpp
src/tokenize.cpp
src/tokenize.h

The pre-suspend barriers were accidentally clubbed together with ckpt barriers and caused the worker to crash.

Bugfix for pre-suspend barriers.

---

src/mtcp/Makefile.debug
src/mtcp/mtcp_restart.c

The commit message is self-explanatory.

3.0 fix restart commit

---

test/plugin/README
test/plugin/presuspend/Makefile
test/plugin/presuspend/README
test/plugin/presuspend/applic.c
test/plugin/presuspend/presuspend.c

To review, do `cd test/plugin/presuspend`.  Read the `README` and maybe do `make check`.
If you want to understand the logic, it might be useful to read the comment at the top of `presuspend.c`.

Add presuspend example to test/plugin

---

src/plugin/pid/pidwrappers.h

Removed already included header

---

include/shareddata.h
src/processinfo.h

This fixes some serialization issues with multi-lib implementation (for #782).

Fixed some serialization data types.

---

test/epoll1.c

The epoll2 test had never worked -- even from when it was created.  It was silently failing to bind, and `perror("bind")` reported "Bad permission", but the process didn't exit.  So, the checkpoint and restart of that trivial process was succeeding, even though our test was failing.
The new Python3-aware version of autotest.py was failing on the old epoll2, but for some reason, the
Python2 running of autotest.py did not turn this  up.
I'm not sure why the two Pythons should give different results.  Apprently, a checkpoint is taken before the epoll2 processes can exit, and checkponit files are created.  But I note that after checkpoint, there is a defunct coordinator left over, and on restart, it tries to use the defunct cocoridnator and hanges, which autotest.py interprets as PASS.  I've …

Fix epoll1.c for epoll2 test; Was silently failing

---

src/plugin/ipc/connectionlist.cpp
src/plugin/pid/pidwrappers.cpp
src/threadlist.cpp

Fix some minor typos (spelling, var. names)

---

src/plugin/ipc/event/eventconnlist.cpp
src/plugin/ipc/file/fileconnlist.cpp
src/plugin/ipc/file/ptyconnlist.cpp
src/plugin/ipc/ipc.cpp
src/plugin/ipc/socket/socketconnlist.cpp
src/plugin/ipc/ssh/ssh.cpp

This is a minor cleanup that mostly involves code movement without any functional changes.

IPC Cleanup to prepare for followup PRs.

---

src/dmtcpworker.cpp
src/dmtcpworker.h
src/popen.cpp
src/threadsync.h

This PR adds a new WrapperLock class that makes lock acquisition in complex wrappers more manageable. This doesn't involve any functional changes yet.

Added WrapperLock class for efficient lock mgmt.

---

src/dmtcp_coordinator.cpp

This was a corner case from pre-suspend barriers.

Coordinator barrier fix

---

include/dmtcp.h
src/dmtcpmessagetypes.h
src/dmtcpplugin.cpp
src/dmtcpworker.cpp
src/plugin/ipc/connectionlist.h
src/plugin/ipc/event/eventconnlist.cpp
src/plugin/ipc/event/eventconnlist.h
src/plugin/ipc/file/fileconnlist.cpp
src/plugin/ipc/file/fileconnlist.h
src/plugin/ipc/file/ptyconnlist.cpp
src/plugin/ipc/socket/socketconnlist.cpp
src/plugin/ipc/socket/socketconnlist.h
src/plugin/pid/pid.cpp
src/plugin/svipc/sysvipc.cpp

There is a minor commit removing some unused functions from the event plugin. Removal of those functions resulted in removal of barriers around those functions.

Converted some global barriers into local.

---

src/plugin/ipc/file/ptyconnection.cpp

It used to be that if the discovered controlling tty (ctty) and stdin were the same, then it would
close the original stdin, and open a new one for the same tty.  Similarly, if the stdin was reading from a pipe or a socket, then we should not close the stdin and re-open it to /dev/tty.  This fix allows the following to work:
```
bin/dmtcp_launch -i5 cat -
cat /etc/passwd | bin/dmtcp_restart ckpt_cat_*.dmtcp
```

Fix stdin/ctty w/ cat FILE|dmtcp_restart ckpt*dmtp

---

util/gdb-add-symbol-files-all

gdb add symbol files-all (fixup)

---

util/gdb-dmtcp-utils

Now, the new GDB command:
```
(gdb) source util/gdb-add-symbol-files-all
(gdb) procfd
```
Does the equivalent of:
```
(gdb) shell ls -l /proc/PID/fd
```

gdb-dmtcp-utils: (add GDB cmd:  add-symbol-files-all, procfd, and more)

---

src/plugin/svipc/sysvipcwrappers.cpp

There was a subtle race condition in our `shmget()` wrapper with two
clients trying to simultaneously create an shm region with `IPC_PRIVATE`
and `IPC_EXCL`.
The code relies on the `VIRTUAL_TO_REAL_SHM_KEY` API, which, in turn,
uses the DMTCP shared data area to share and assign unique keys for SysV
shm regions. The API returns -1 if the key does not exist in the DMTCP
mapping. Now, if one client raced ahead and managed to create the region,
it'd end up populating the DMTCP shared area with a "IPC_PRIVATE ->
realKey" mapping. Later, when the other client would try to create its
own shared memory region, the `VIRTUAL_TO_REAL_SHM_KEY` API would return
the key corresponding the earlier created entry and the `shmget(IPC_EXCL)`
call would fail with an `EEXIST` error.
The fix here is to detect …

sysvipc: Fix a race with two clients creating shm with IPC_PRIVATE

---

src/dmtcp_restart.cpp
src/plugin/ipc/ssh/dmtcp_ssh.cpp
src/plugin/ipc/ssh/dmtcp_sshd.cpp
src/plugin/ipc/ssh/util_ssh.cpp
src/util_init.cpp
src/writeckpt.cpp
test/openmp-1.c
test/posix-mq1.c
test/posix-mq2.c
test/procfd1.c
test/pthread4.c
test/timer2.c

sys/errno.h -> errno.h
sys/fcntl.h -> fcntl.h

Add include files required by POSIX/and gcc warnings (part 2)

---

configure
configure.ac

This is a bug fix to configure.ac.  The bug was introduced in commit c6d50c0ae04.  It's my fault -- I used AC_PATH_PROG incorrectly.  This is a fix for PR #805.  It should be trivial to review.

configure.ac: MPICH_MPICC: Bug fix: c6d50c0ae04

---

test/autotest.py

This now provides:  `./autotest.py --parallel`
The tests are run with up to `PARALLEL_JOBS` jobs (currently 5).  It works by creating `PARALLEL_JOBS` child processes in backgrouind executing `./autotest.py NEXT_TEST`.  If the test fails or has not completed, then the child process is killed and the original process re-executes it in the foreground.
In this PR, `make check` does not yet use the `--parallel` option.  It's best to commit this PR first, and get some confirmation that it is robust.  But that should also work.

Add '--parallel' option to autotest.py

---

src/rwlock.cpp

RWLock: Don't release mutex after acquiring wrlock.

---

src/mtcp/mtcp_restart.c
src/mtcp/sysdep/sysdep-x86_64.h
util/readdmtcp.sh

This should be trivial to review.  It's two improvements to the English text, and a minor fix to a file, to avoid a compiler warning.

Polish some of the English text

---

src/writeckpt.cpp

The DMTCP type 'Area' assumes the invariant that `area.addr + area.size == area.endAddr`.  This invariant was not satisfied in original commit f01c3009 from 2014.  `area.size` was updated, but not `area.endAddr`.
@xuyao0127 encountered this bug when working on MANA.  Earlier, @rohgarg encountered this bug in the initial commit for MANA, but did only a local fix by switching from `area.endAddr` to `area.addr + area.size`.

Fix commit f01c3009: bug in writememoryarea

---

src/writeckpt.cpp

The segfault occurred because area.addr is `char *` and JTRACE treats `char *` pointers as string.

Fixed area->addr typecasting for JTRACE.

---

.gitignore
test/autotest.py

Minor update to .gitignore file.

Disabled vfork tests in autotest.py.

---

contrib/snooze/snooze.c
include/dmtcp.h
src/coordinatorapi.cpp
src/coordinatorapi.h
src/dmtcpnohijackstubs.cpp
src/dmtcpplugin.cpp
src/execwrappers.cpp

Removed some deadcode.

---

src/plugin/svipc/sysvipc.cpp
test/sysv-shm2.c

Application may call shmat at some area followed by a munmap call. While unconventional, this is allowed, and we should simply remove that area from our tracking map.

Allow application to munmap SysV SHM area.

---

src/plugin/ipc/file/fileconnection.cpp
src/plugin/ipc/file/fileconnection.h
src/plugin/pid/pid.cpp
test/autotest.py
test/procfd1.c

Updated procfd1 test with /proc/self/task/<tid>/maps file example.

Handle /proc/self/task/* files.

---

src/plugin/svipc/sysvipc.cpp

If a shared memory segment is marked deleted, the kernel gives a **different** shmID with the same key. It creates more than shm regions in the process address space with the same key but different shmIDs.
However, DMTCP doesn't mark deleted while restoring the shm areas, and the kernel gives the **same** shmid to DMTCP. This PR handles this use case.
[Clarification added by gc00:  "If a shared memory segment is marked deleted," means: `shmctl(shmid, IPC_RMID, NULL);` was called.]

Handle deleted shm area case

---

src/plugin/ipc/file/fileconnlist.cpp

Instead of writing to a file and remapping it, if a file has been unlinked prior to checkpointing, there's no reason to write back to that file. Instead open and immediately unlink the file, then refill the memory segment contents

Fixed handling of unlinked and deleted files on restart

---

include/dmtcp.h
jalib/jalloc.cpp
src/coordinatorapi.cpp
src/coordinatorapi.h
src/dmtcp_launch.cpp
src/dmtcp_restart.cpp
src/dmtcp_restart.h
src/dmtcpnohijackstubs.cpp
src/dmtcpplugin.cpp
src/dmtcpworker.cpp
src/plugin/ipc/socket/socketconnection.cpp
src/processinfo.cpp
src/processinfo.h

Also removed fred_record_replay bits from jalloc.cpp.

Removed some stale code related to --no-coordinator.

---

NEWS
test/plugin/example-db/README
test/plugin/presuspend/README
test/plugin/presuspend/presuspend.c

I've added a NEWS release for the 3.0 version.  After you review (and approve?) this PR, please don't push it in yet.  I'd like to review the text, and then push it in myself after I've reviewed it.
Please do add or fix anything that I've forgotten.  It's been a long time since the last formal release.

Added to NEWS for 3.0.0 release

---

include/dmtcp.h
jalib/jassert.cpp
src/dmtcp_launch.cpp
src/mutex.cpp
src/plugin/pid/pid.cpp
src/rwlock.cpp
src/threadlist.cpp
src/util_misc.cpp
src/writeckpt.cpp

Fix a bunch of random compiler warnings

Fix compiler warnings

---

src/mtcp/mtcp_restart.c
src/mtcp/mtcp_restart.h

The title says it all.
Recently, review times have been extending to two or three weeks, and I need this earlier, for the sake of MANA.  So, I'll be pushing it in directly.

Add maxHighMemEnd in mtcp/mtcp_restart.c

---

test/autotest.py
test/syscall-tester.c

Let's give this a quick review, so that github 'check status' will no longer choke on syscall-tester during the "build tests".  This should finallly fix syscall-tester.
@karya0 , Even if @xuyao0127 manages to review this first, could you also look at this for purposes of design?  If the design looks good, I'm thinking of implementing `--checkpoint-all-files-as-precious` as described.  (Also, is that a good name for the flag?)
* See the TODO comment in syscall-tester.c
* This fix is hardwired for syscall-tester.  As in the TODO, we should implement:  dmtcp_launch --checkpoint-all-files-as-precious
* We have seen real-world examples that create and delete many small files in a directory as an impromptu database.  We need a fix like this to support such cases.
* And these types of examples …

Fix syscall-tester.c correctly (but still a hack)

---

src/dmtcp_launch.cpp
test/syscall-tester.c

fsgsbase is used only on x86_64; add #ifdef

---

src/dmtcp_coordinator.cpp

Add another fix for "stale timeout"
* Also add FIXME comment about cleaner future logic

Fix "stale timeout" again (commit d487881)

---

util/gdb-dmtcp-utils.py

Enahcing `gdb-dmtcp-utils.py` again.
`load-symbols-library` can now also take two arguments.
```
(gdb) help load-symbols-library
load-symbols-library [FILENAME-OR-ADDRESS] [ADDRESS[ (loads symbols)
With no argument, it loads symbols for the newest call frame that has no name.
With 1 argument, specify filename or address; /proc/*/maps must have filename.
With 2 argument2, specify filename and address; /proc/*/maps may have\
no filename; ADDRESS may be given as '$pc'.
```

Enhance gdb-dmtcp-utils.py: "[NO_LABEL]" and "$pc"

---

jalib/jfilesystem.cpp
src/ckptserializer.cpp
src/dmtcpplugin.cpp
src/dmtcprestartinternal.cpp
src/ldt.h
src/membarrier.h
src/miscwrappers.cpp
src/mtcp/mtcp_check_vdso.c
src/mtcp/mtcp_restart.h
src/mtcp/mtcp_sys.h
src/mtcp/sysdep/sysdep-riscv.h
src/plugin/pid/pid_miscwrappers.cpp
src/plugin/pid/pidwrappers.h
src/shareddata.cpp
src/threadinfo.h
src/threadlist.cpp
src/tls.cpp
src/util_exec.cpp

This branch is the same as the previous RISC-V branch, but I have split one large commit into several smaller ones.

Riscv dmtcp experiment

---

src/dmtcp_coordinator.cpp

@karya0 ,
Can you give this PR a quick review.  I'm really eager to do the DMTCP 3.1.0 release.  But I discovered only today that in my last commit for `dmtcp_coordinator`, I fixed one bug and created another bug.  I believe this PR now fixes both bugs.
It's been a continuing problem to make dmtcp_coordinator work with `--stale-timeout`.  But without that, we have old `dmtcp_coordinator` processes sitting around and blocking the '7779` port.  I tore out some of my old spaghetti code and hopefully have fixed this now, in some clearer code.
Earlier, 'dmtcp_command -c' worked (and hence 'make check', but not the '--interval' ('-i') flag:
> 'dmtcp_launch --interval' and 'dmtcp_coordinator --interval'
showed the correct interval in 'dmtcp_command --status',
but the coordinator was not …

'dmtcp_launch --interval' and 'dmtcp_coordinator --interval' now fixed

---

src/dmtcprestartinternal.cpp

Add comment for dmtcprestartinternal.cpp update

---

src/dmtcp_coordinator.cpp

MANA uses `dmtcp_coordinator --status-file`.  Let the coordinator write the start and exit date/time in human-readable fashion.  This will help MANA or people to delete obsolete files.

dmtcp_coordinator --status-file: started/exited

---

src/dmtcpworker.cpp
src/execwrappers.cpp
src/util_misc.cpp
test/forkexec.c

* Exec error handling.
* getTimestampStr deadlock handling.

A few bug fixes related to exec and initialization.

---

src/dmtcp_coordinator.cpp

When processing epoll_wait events, EPOLLIN should be processed before EPOLLHUP. This ensures no messages are dropped if a client disconnects immediately after sending a message.

Coord: Fixed epoll_wait corner case.

---

jalib/jfilesystem.cpp
jalib/jfilesystem.h

Use sys_getdents64 and linux_dirent64 on 64-bit machines.

Use linux_dirent64 type with sys_getdents64

---

src/dmtcprestartinternal.cpp
test/autotest.py

PR https://github.com/dmtcp/dmtcp/pull/1207 needs to be merged before this PR.

FIxed --restartdir flag
