- test/autotest.py
This patch adds a fix for a bug in the autotest.py script
that would preclude slower CPUs from having extra time
for process start up. The problem was because of the
extra whitespace characters in the output of `uname -m`
used by the script to detect the architecture.
> Minor fix for autotest script

- src/mtcp/mtcp_restart.c
- test/autotest.py
- test/file1.c
- test/file2.c
- test/shared-memory1.c
- test/shared-memory2.c
If an application like Open MPI created a directory tree in a temp directory, and then unlinked its files and directories, DMTCP fails to restore.  (DMTCP does work correctly, if there is only a deleted file and no deleted directories.)  This addition will call fix_parent_directories() both for MAP_SHARED and for the standard files mapped private.
This addition also creates shared-memory2.c and file2.c to test the code.  Unfortunately, the file2.c test exposes a corresponding bug in fileconnection.cpp.  So, file2 has not yet been added to autotest.py.
> In mtcp, fix restoring of deleted directory tree (and add new tests)

- test/autotest.py
Check Python variable USE_M32, and skip any tests in m32 mode that invoke 64-bit processes.
> If m32, skip tests of autotest on 64-bit apps

- doc/debugging-dmtcp.txt
- jalib/jassert.cpp
JASSERT doesn't generate a coredump by default. This patch
introduces a new DMTCP environment variable:
DMTCP_ABORT_ON_FAILED_ASSERT.
Exporting this variable will cause JASSERT to call abort()
to generate a coredump. This can be useful when debugging
distributed applications.
> JALIB: Generate coredumps on JASSERT

- plugin/modify-env/Makefile.in
- plugin/modify-env/test.c
This patch fixes the broken `make check` for the modify-env plugin.
> modify-env-plugin: fix Makefile and test

- src/plugin/ipc/socket/socketconnection.cpp
This is a workaround for the random ckpt bug at Stampede.
> socketconnection: add PMI socket to blacklisted sockets

- src/mtcp/mtcp_restart.c
At Stampede, when more than one process on one node share the same deleted shared-memory file, the unlink in mtcp_restart() would cause a race condition. This is just a temporary fix to make it work.
> Temporary fix for deleted shm file at Stampede.

- src/plugin/ipc/file/fileconnection.cpp
- src/plugin/ipc/file/fileconnection.h
- src/util_misc.cpp
Some systems _prepend_ " (deleted)" instead of doing an _append_. This was observed on travis ci builds (https://travis-ci.org/dmtcp/dmtcp/builds/70006651).
> Better handling of deleted files.

- src/plugin/pid/pidwrappers.cpp
- src/processinfo.cpp
On older systems, a process is inherited by init (pid = 1) after its
parent dies. However, with the new per-user init process, the parent
pid is no longer "1"; it's the pid of the user-specific init process.
The current process is the root-of-process-tree, if the current ppid is
different than the previous one.
> Fix updating root-of-process-tree after parent exits.

- src/plugin/alloc/alloc.h
- src/plugin/alloc/mallocwrappers.cpp
This patch replaces the call to _real_memalign() in the
valloc wrapper (in the alloc plugin) with a call to
_real_valloc(). The call to memalign() imposes a runtime
overhead of up to 600 percent.
> valloc: replace memalign with valloc

- src/dmtcp_coordinator.cpp
This code sets a local variable, `newState`, and it never uses it.  The code seems to have been added to DMTCP in October, 2013 as commit 6aeee7005fad4f4c92c9586ac47bff58bd16f9d5.  But even in that commit, the code does not seem to use the local variable `newState`.
@karya0, you had added this code in 2013.  The log message says something about the intention of the commit, but it doesn't seem to have any effect.  Shall we delete this code as orphan code?
> Delete orphan code in coord (newState not used)

- include/dmtcp.h
- src/dmtcp_coordinator.cpp
- src/dmtcpplugin.cpp
- src/dmtcpworker.cpp
- src/plugin/ipc/connectionidentifier.cpp
- src/processinfo.cpp
- src/processinfo.h
- src/shareddata.cpp
- src/threadlist.cpp
- src/uniquepid.cpp
- src/uniquepid.h
- test/plugin/applic-delayed-ckpt/applic.c
- test/plugin/applic-initiated-ckpt/applic.c
The function `dmtcp_get_generation()` in `include/dmtcp.h`.  Sometimes gives the wrong answer.  This fixes the bug.  In addition, a function `checkpoint_is_pending()` was added in the last of the commits.
I can optionally remove the function `checkpoint_is_pending()`, but the implementation is tiny, and it seems like it might be useful in the future.
The reason for the original bug is that the DMTCP generation (number of checkpoints so far) is maintained by the coordinator for the whole computation.  This is as it should be.  But on each host, the sharedDataHeader keeps one copy of the generation in shared memory for all processes on the same host.  This means that when a checkpoint request from the coordinator arrives at one process, it will update the generation even before the other …
> Fix dmtcp_get_generation()

- src/dmtcp_coordinator.cpp
`dmtcp_launch -i5 test/dmtcp1` causes the coordinator to do busy waiting during the checkpointing sequence.  This slows down a client on the same host, which is trying to use the CPU to do the checkpoint.  See issue #165 for a detailed analysis of the cause, and why this one-line patch fixes it.
> Coordinator is CPU hog during checkpointing when using interval timer

- src/Makefile.am
- src/Makefile.in
- src/ckptserializer.cpp
- src/ckptserializer.h
- src/dmtcp_restart.cpp
This pull request includes two commits.  The first and larger one moves four functions from ckptserializer.cpp to dmtcp_restart.cpp:
first_char(), open_ckpt_to_read(), CkptSerializer::openCkptFileToRead((), CkptSerializer::readCkptHeader()
They all become static functions in dmtcp_restart.cpp, since no other file refers to them.  (And of course, they are no longer methods of the CkptSerializer class.  This also makes logical sense, since the name ckpserializer.cpp refers to serializing files.  The files that were moved are used to inspec the already created checkpoint image file on restart, and so they are conceptually different.
&nbsp;&nbsp;&nbsp;&nbsp;And finally, the biggest win is that the four functions included about 12 occurrences of `_real_XXX()`.  The dmtcp_restart executable has …
> Simplify dmtcp_restart (no need for wrapper fncs or _real_XXX())

- test/plugin/applic-delayed-ckpt/Makefile
- test/plugin/applic-initiated-ckpt/Makefile
- test/plugin/example-db/Makefile
- test/plugin/example/Makefile
- test/plugin/sleep1/Makefile
- test/plugin/sleep2/Makefile
In the test/plugin examples, kill any old coordinator using `${DEMO_PORT}` as first step of `make check`.
> Enhance test/plugin/*/Makefile; kill old coordinator

- test/autotest.py
The commit message and associated autotest comment (below) say it all:
The error exposed on second restart is described in https://github.com/dmtcp/dmtcp/issues/167#issuecomment-130439439.
I set `S=10*DEFAULT_S` for this test to expose the bug.
This is needed to expose a pre-existing bug.  Pull request #170 fixed some bugs associated with shared-memory, but we didn't notice this additional bug due to the lack of an appropriate test.
> Allow more time for shared-memory tests

- Makefile.in
The diff of the file is short and self-explanatory.  To see what we're trying to protect against, add
a new file src/config.h that includes just one line:
#error "TESTING.  WE SHOULD NEVER REACH HERE."
and do:  `make clean && make -j`
Such a bug actually happened to me, because I was playing with different revisions of DMTCP, and
ended up with a stray src/config.h that was left over from before the commit of March 24, 2015: 68bf006838740db5ea1bfedeff76cfa1e05c04d7 .  By deleting a stray src/config.h on builds, we avoid such brittleness.
> Remove stray src/config.h for greater robustness

- src/mtcp/mtcp_check_vdso.ic
- src/mtcp/mtcp_restart.c
- src/plugin/ipc/file/fileconnection.h
- src/procselfmaps.cpp
- src/shareddata.cpp
All of these changes were suggested by warnings when compiling
with the clang-3.4 compiler.  Most are self-explanatory.
Here are reasons for two of the more obscure changes:
1. shareddata.cpp :  size_t -> int
size_t is an unsigned data type.  So, the i>=0 condition is always true.
This is a bug, since we want to allow i-- to cause i to become negative, and return false in that case.
2. procselfmaps.cpp
ProcSelfMaps::ProcSelfMaps() initializes the private field members in a certain order.  But in include/procselfmaps.h, those fields were declared in a different order.
Clang warns about this.  Now the initialization respects the order in which the fields were declared.
> Minor polishing suggested by warnings from clang

- src/plugin/ipc/file/fileconnection.cpp
This bug fix will address the first half of issue #167 (shared-memory1 on NFS machines).  It does *not* address the second half of the issue (from the 16-core test machine).  (The second half of the issue concerns a spurious JWARNING.) 
This is a patch to the logic of commit e03f2727ef8fdde45d79 in pull request #170.
@karya0, could you please ta look at this one-line fix, since it concerns your code?  Thanks.
> Fix for bug, under NFS, exposed by shared-memory1

- src/plugin/ipc/file/filewrappers.cpp
- src/plugin/pid/pid_filewrappers.cpp
- test/autotest.py
- test/stat.c
In a user's program, stat() was being called with a bad memory address for pathname.  The combination of libc and the kernel then returned -1 with `errno == EFAULT`.
&nbsp;&nbsp;&nbsp;&nbsp;Under DMTCP, stat() went through a wrapper, which tried to read the memory at the address of the pathname.  Because of this it segfaulted.  Now, our utilities updateStatPath() and updateProcPathVirtualToReal() check if the memory address is readable before reading it.
&nbsp;&nbsp;&nbsp;&nbsp;A test program, stat.c, has been added that used to fail under DMTCP.  It now works.
(This pull request address issue #102.)
> __xstat() survives bad mem addr

- test/Makefile.in
@karya0 and @rohgarg, There is one issue to note here, in a fix to test/Makefile.in.  The `--enable-debug` flag was intended to set the `DEBUG` macro in the `src` directory.  But since `DEBUG` is also used in the test directory, and maybe elsewhere, we end up turning on `DEBUG` where we don't intend to.
This bug fix adds `-UDEBUG` to `CFLAGS` in `test/Makefile.in`, to turn off any previous `-DDEBUG` flag.
A different and probably better bug fix would be to create a configure variable, `@DEBUG@`.  We would then write:
CFLAGS = @DEBUG@ @CFLAGS@
in `src/Makefile.in` and all of its subdirectories.  But in `test/Makefile.in`, we would use only:
CFLAGS = @DEBUG@ @CFLAGS@
Then, `test/Makefile.in` would set `@DEBUG@` instead of modifying `@CFLAGS@`.  This alternative bug fix actually seems like a …
> Make --enable-debug work again

- include/dmtcp.h
- src/mtcp/mtcp_restart.c
This is joint work between Pranay Surana and myself.  There were two bugs, due to weaker support from clang.  This provides workarounds.  It was tested against clang-3.4.
1. dmtcp.h : clang-3.4.1 was converting some static local variables into weak variables when they were inside the function `dmtcp_event_hook()`, which is declared weak.  It appears that clang-3.4.2 fixes this.
2. mtcp_restart.c : This is compiled with -O0.  Apparently, clang uses the ebp/rbp register in the epilog to `estart_fast_path()`, and we were zeroing it out just before returning.
> clang-3.4 failed on launch, & on restart; fixed

- src/dmtcp_coordinator.cpp
> fixup! Use alarm() for interval checkpointing.

- src/syscallsreal.c
It was tested on HiKey 96 boards, running 8-core Cortex-A53 SoC.
The early armv8 code fails on this.  But the standard code works.
@rohgarg, this is the patch that we discussed.  Could you review this pull request, and approve it if it agrees with what we proposed?  Thanks.
> Code for early armv8 w/ pthread was failing on new armv8's (now fixed)

- src/coordinatorapi.cpp
- src/dmtcp_coordinator.cpp
- src/util_init.cpp
- The problem was that launch called the coordinator, which  was not quiet.
- The first step was to revert most of commit 7bdf16b3, which had
made the --quiet flag do nothing.
- The second step was to look for 'JASSERT_STDERR <<' in dmtcp_coordinator.cpp
and wrap it in 'if (! quiet)'.
**QUESTION:**
In coordinatorapi.cpp::439, we always pass on the flat ``--quiet`` if ``dmtcp_launch`` is starting a new coordinator.  We do this because the coordinator will be in the same window as the target process, and we don't want the coordinator output interfering.  We did this even if `dmtcp_launch` was not called with ``--quiet``.  I like this policy, and this PR continues that policy.  Are we agreed on this?
> dmtcp_launch --quiet is now truly quiet

- src/plugin/svipc/sysvipcwrappers.cpp
An application can call semctl({IPC|SEM}_INFO) directly to
fetch the information about system-wide semaphore limits
and parameters. In this case, the values of the first two
arguments to semctl() -- semid and semnum -- are irrelevant,
and the application can pass invalid or negative values.
Consequently, DMTCP will assert and exit if it tries to get
the real ids for such invalid values.
This patch adds a case for these two commands in the semctl
wrapper to avoid the above mentioned problem.
> sysvipcwrappers: Fix {IPC|SEM}_INFO cases for semctl

- src/plugin/svipc/sysvipc.cpp
- src/plugin/svipc/sysvipc.h
The sysvipc class uses a STL map to map virtual semaphore
ids to semaphore objects. The on_semget() method, which is
called on every semget(), was using the the real semaphore
ids as keys to read the values, whereas the STL map maps
virtual sem. ids to semaphore objects.
This fixes issue #205.
> sysvipc-plugin: Fix a bug in on_semget()

- src/threadlist.cpp
The issue arose due to a recent commit: 0523b46, in which
procname related code (from src/procname.cpp) was moved into the
stopthisthread signal handler (in src/threadlist.cpp), but the
relevant header file: `<sys/prctl.h>` that is required for prctl()
was never moved out of the conditional in threadlist.cpp. This
results in a compilation failure on RHEL-5.8.
> threadlist.cpp: Fix compilation error for prctl

- src/dmtcpplugin.cpp
- src/mtcpinterface.cpp
- src/mtcpinterface.h
The broken dmtcp_checkpoint() was reported separately by two DMTCP
users.
The commit 823d096 removed all references and the definition of the
function `dmtcp::userHookTrampoline_postCkpt()`.  The removal of
`userHookTrampoline_postCkpt` also removed calls that incremented the
static global variables `numRestarts` and `numCheckpoints`. Consequently,
the calls to `dmtcp_checkpoint()` would get stuck in a while loop in
`dmtcpplugin.cpp`.
This patch fixes the problem by adding a call to increment the global
counters post checkpoint.
Fixes issue #215.
> Fix broken dmtcp_checkpoint() API

- test/plugin/applic-delayed-ckpt/Makefile
- test/plugin/applic-initiated-ckpt/Makefile
- test/plugin/example-db/Makefile
- test/plugin/example/Makefile
- test/plugin/sleep1/Makefile
- test/plugin/sleep2/Makefile
We kill an old coordinator using dmtcp_command at the beginning of 'make check'.  But a JWARNING message goes to stderr.  This patch redirects:  2>/dev/null
An alternative would be to add a`--quiet` flag to `dmtcp_command`.  But that seems like overkill to me.
> Clean up test/plugin/*/Makefile: make check

- src/restartscript.cpp
size_t variable requires format of %zu.  One occurrence had `%zd` and the other occurrence had `%d`.
Note that while this is part of C99,  But C++ compilers tend to support this, since they need to read C-based include files.
> Change size_t variable from %d to %zu (& %zd->%zu)

- src/execwrappers.cpp
This patch fixes a bug in the `copyEnv()` code where we
would dereference a NULL pointer if the environment
argument of an `execve()` call was NULL.
> execwrapper.cpp: Fix null pointer dereference when env is NULL

- src/plugin/ipc/connectionlist.cpp
The locks were incorrectly acquired inside the if block. This fix ensures that
the locks are acquired for the whole duration of the function call.
> Fixed a race with simultaneous calls to close.

- include/dmtcp.h
- src/dmtcpplugin.cpp
Many functions declared in dmtcp.h are not really usable by
an end-user because they are not correctly declared.
This patch fixes the issue for functions related to setting
the checkpoint directory path and the coordinator scripts
directory path.
> dmtcp-api: Expose some existing functions

- include/dmtcp.h
VOID is a commonly used macro in programs. For application-
initiated checkpointing, the use of VOID in dmtcp.h can conflict
with names used by end users.
This patch replaces references to the VOID macro in the dmtcp.h
header file with DMTCP_VOID.
> dmtcp.h: Change VOID to DMTCP_VOID

- src/coordinatorapi.cpp
- src/threadlist.cpp
More generally, sem_launch (formerly sem_start) was being posted too early,
while the checkpoint thread was still active
See github issue #247 for further background on this PR.
> Fix race in: dmtcp_launch --no-coordinator tcsh

- configure.ac
I remove a configuration section from configure.ac that forces g++ to be installed.  This is leftover from an early version of the file, and AC_PROG_CXX now checks for any available C++ compiler, instead of insisting on g++.
I didn't do autogen.sh and push in the corresponding configure file.  Since this is for version 2.5.0, someone else will inherit this configure.ac and do a new configure in time for version 2.5.0.  :-)
> Don't require g++; AC_PROG_CXX already does the general case

- src/nosyscallsreal.c
Modifies `nosyscallsreal.c`.  This eliminates the following warning message:
```
In file included from nosyscallsreal.c:46:0:
syscallwrappers.h:476:47: warning: ‘struct msqid_ds’ declared inside parameter list
int _real_msgctl(int msqid, int cmd, struct msqid_ds *buf);
```
> Fix for 809b4fd1; eliminates warning for 'struct msqid_ds'

- src/coordinatorapi.cpp
- src/dmtcp_launch.cpp
`dmtcp_launch --no-coordinator` should fail when target application calls fork(), since the coordinator is embedded in a single process.  But our error message did not make it clear why this happens.  This improves the JASSERT message and also the documentation for `dmtcp_launch -h`.
This issue is discussed as issue #245.
> Improved error message/--help for --no-coordinator

- src/mtcp/mtcp_check_vdso.ic
This pull request was suggest by @loveshack.  It fixes a misleading error message in vdso.c when DMTCP tries to set the resource limit for the stack on restart.  This was raised originally as issue #240.
> Improve stack limit error message in vdso.c

- test/Makefile.in
- test/autotest.py
- test/dlopen1.c
- test/dlopen2.cpp
Fixes test/Makefile.in (It wasn't building libdlopen-lib3.so due to a typo).
It also polishes the dlopen1/dlopen2 tests.
> Build dlopen2 test correctly

- contrib/infiniband/ibv_internal.h
- contrib/infiniband/ibvctx.c
The memory leak leads to a weird segfault during MPI_Finalize().
> IB: Fix the memory leak when freeing device list.

- contrib/infiniband/Makefile.in
- contrib/infiniband/README
- contrib/infiniband/infinibandwrappers.c
We link the plugin with the verbs library, and when the application
calls dlopen() to open libibverbs.so, we dlopen() the plugin in
the wrapper for dlopen(), so that all subsequent verbs calls will
fall in our verbs wrappers.
> Fix the bug when dlopen() is used to open ib verbs

- src/restartscript.cpp
The dmtcp_set_coord_ckpt_dir("dirname") API is used to specify
the location where the restart scripts are written.
This patch fixes an issue with the API where specifying a
relative path would set up the dmtcp_restart_script.sh symbolic
link incorrectly. If a relative path, say ./a/b/c, was specified,
DMTCP would create the symbolic link (in the ./a/b/c directory)
that pointed to ./a/b/c/dmtcp_restart_script_XXX.sh instead
of ./dmtcp_restart_script_XXX.sh.
> restartscript: Fix dmtcp_restart_script.sh symbolic link set up

- src/dmtcp_nocheckpoint.c
- src/dmtcpworker.cpp
- test/autotest.py
- test/nocheckpoint.c
dmtcp_nocheckpoint was unsetting LD-PRELOAD, even if the user had a value for LD_PRELOAD.
* This copies `dmtcpworker.cpp:restoreUserLDPRELOAD()` into `dmtcp_nocheckpoint.c` and uses it.
* In the second commit, this creates a test for dmtcp_nocheckpoint to verify that it is saving the user's LD_PRELOAD.
> Fix dmtcp_nocheckpoint

- src/dmtcp_restart.cpp
Fixes ee6c20df4 (i.e., better fix for 7a3086bbc62)
As the FIXME says,
```
// FIXME: This is needed for CONFIG_M32 only because getPath("mtcp_restart")
//        fails to return the absolute path for mtcprestart.  We should fix
//        the bug in Util::getPath() and remove CONFIG_M32 condition in #if.
```
The logic will use `lib/dmtcp/32/lib/dmtcp/mtcp_restart-m32`, when it should use `lib/dmtcp/mtcp_restart` in the case of standalone 32-bit DMTCP.  This is a minimal fix, to go into DMTCP 2.4.4.  A full fix can go into DMTCP 2.5.0.
I'm also pushing this in without review, because it is needed now for PR #274 .
> Fix prev. bug in multi-arch logic

- include/procselfmaps.h
- jalib/jalloc.cpp
- jalib/jalloc.h
- src/procselfmaps.cpp
- src/writeckpt.cpp
If the JAlloc allocator expands its memory, it will call mmap().  If this happens while reading `/proc/self/maps`, it will create a bug on restart.  The allocator will have saved a pointer to the freshly mmap'ed memory, but since it was mmap'ed after reading `/proc/self/maps` and before we copied memory into the checkpoint image, we will have a dangling pointer into memory that has not been saved.
This bug appears when doing either of:
```
make -j AUTOTEST=--stress check-pthread5
make -j AUTOTEST=--stress check-shared-memory1
```
> Fix race while reading /proc/self/maps for ckpt

- test/autotest.py
This should be trivial to review.  The test for `autotest.py` was written a while ago, but we had not been allowing enough time for the test to complete in the past.
> Add test/file2.c: the test opens file and dirs and unlinks

- src/dmtcp_restart.cpp
`dmtcp_restart --help` says that `--ckptdir` and the environment variable `DMTCP_CHECKPOINT_DIR` can both be used to set the checkpoint directory.  But only `--ckptdir` was implemented.  This now also implements the environment variable `DMTCP_CHECKPOINT_DIR`.
> dmtcp_restart: obey DMTCP_CHECKPOINT_DIR env var

- test/autotest.py
- test/environ.c
Test if environ is saved across a checkpoint/restart.
> Add test if environ saved across ckpt/restart

- src/plugin/ipc/ipc.h
- src/plugin/ipc/socket/socketconnection.cpp
- src/plugin/ipc/socket/socketconnection.h
- src/plugin/ipc/socket/socketconnlist.cpp
- src/plugin/ipc/socket/socketwrappers.cpp
Added a new TCP type, TCP_CONNECT_IN_PROGRESS, that indicates a
non-blocking connect. During drain, we call select() to check whether
the socket is writable or not. If it's still not writable after 60
seconds, we mark the socket as external and continue.
> Added support for non-blocking connect.

- src/plugin/svipc/sysvipcwrappers.cpp
This one-line fix should be trivial to review.
A DMTCP user had reported that in Fall, 2015.  This fix was buried in the larger PR #238, but this fix should be added to DMTCP-2.4.5.  So, I'm separating this out as a separate PR.
> Handle conflicting msgrcv type for SLES10

- include/dmtcp.h
- src/dmtcpplugin.cpp
- src/dmtcpworker.cpp
- src/syscallsreal.c
- src/syscallwrappers.h
- Consolidated wrapper initialization to syscallsreal.c.
- Removed dmtcp_is_initializing_wrappers() API from dmtcpplugin.h.
- Fixes #290.
> Updated wrapper initialization code.

- plugin/modify-env/modify-env.c
- plugin/modify-env/warning.cpp
The title shows what this PR does.
Ideally, the code would also check if the `"DMTCP_QUIET"` environment variable was set prior to checkpoint.  But when the code calls `getenv("DMTCP_QUIET")` at restart time, the result always points to an unmapped address.  (Note that prior to checkpoint, DMTCP sets this environment variable to the string "0" if the environment variable had not been set.  But the pointer to the string "0" is being corrupted when the plugin tries to test for it during restart.)
Therefore, the current code has commented out the test for `"DMTCP_QUIET"`.
> modify-env plugin now warns if no "dmtcp_env.txt"

- test/Makefile.in
- test/autotest.py
- test/mutex1.c
- test/mutex2.c
- test/mutex3.c
- test/mutex4.c
These tests for autotest will be used to test the new mutex wrapper code in PR #282.  The tests will fail without PR #282.  So, this should not be pushed in until PR #282 has been pushed.
These tests are for recursive mutexes only.  In my cursory testing, I didn't see a bug appear with normal mutexes.  @rohgarg and @ankitcse07 report that they have an example of a bug that also affects normal mutexes.  I will add a test file for normal mutexes into this pull request when I find those examples again (or when they re-send them to me :-) ).
> Add tests for mutex (esp. recursive mutex)

- configure
- configure.ac
- src/Makefile.am
- src/Makefile.in
This configure option causes $CXX to use the g++ flag `-static-libstdc++`
When a newer and older distro share a filesystem, and when
g++ builds on the newer distro, then the executable fails on
the older distro.  This should fix it.
An explanation of the problem occurs here:
https://hosunghwang.wordpress.com/2015/07/15/libstdc-so-6-library-mismatch-problem-and-solution/
(except that the author meant to refer to `-static-libstdc++` at the end of the article).
I haven't yet found a testing machine with the right packages to test this.  So, it's not yet ready to be pushed in.
> configure: --enable-static-libstdcxx

- configure
- configure.ac
This pull request fixes some of the C programs being tested.  They were missing some include files.
The pull request is meant to be committed after PR #229.  For that reason, the configure.ac and configure file here also include changes made within PR #229.
> Fix warnings in configure tests (include files)

- plugin/Makefile.am
- plugin/Makefile.in
This fixes an earlier commit to provide warnings when using plugin/modify-env
> Fix Makefile for prev commit:  3a53d4f676ed

- src/siginfo.cpp
This fixes an issue with programs that use pthread_cancel() reported by
a DMTCP user.
At the time of checkpoint, DMTCP saves all signal handlers using libc's
sigaction() call. Then, DMTCP saves the per-thread signal mask using
libc's pthread_sigmask() call.
On restart, DMTCP first restores the signal handlers of the process
using libc's sigaction() function. And finally, it restores the signal
mask using libc's pthread_sigmask() call.
The NPTL library uses SIGCANCEL (signal #32) and SIGSETXID (signal #33)
internally. The corresponding signal handlers are installed when the
library is initialized by the Linux dynamic linker/loader when loading
a target application that's linked against libc.
The root cause behind the issue is that libc prevents any request that has
anything to do with the …
> siginfo: Save/restore signal handlers using _real_syscall

- configure
- configure.ac
In configure.ac (and configure), on older versions of readelf, `/usr/bin/readelf -aW /usr/bin/readelf | grep interpreter` produced two hits for the possible name of the ELF interpreter.  Now we do `/usr/bin/readelf -aW /usr/bin/readelf | grep 'interpreter.*]'` to capture only the intended match.
This is a fix for issue #320.  It should be pushed into both 3.0 and into 2.4.5.  I will label it for milestone 2.4.5, since that's the earlier version needing this fix.  However, this commit is the one that is applied to the 3.0 branch.
> Fixes configure bug for interpreter=`...`

- src/threadwrappers.cpp
This is a duplicate of PR #330 for the 2.5 branch.
> threadwrappers: Fix segfault when clone call fails

- src/dmtcp_coordinator.cpp
This patch fixes an issue with the checkpoint time reported
by the coordinator when using the --exit-on-checkpoint flag.
> dmtcp_coordinator: Fix checkpoint timing when using --exit-on-checkpoint

- include/procmapsarea.h
- src/constants.h
- src/mtcp/mtcp_restart.c
- src/procselfmaps.cpp
- src/writeckpt.cpp
@gc00 @rohgarg @jiajuncao: Can you take a look at it and see if that works for you?
The optimization is enabled by setting `DMTCP_SKIP_WRITING_TEXT_AREA=1` environment variable.
> Skip saving text area to ckpt image

- src/dmtcp_coordinator.cpp
This patch fixes an issue with the coordinator where
it would fail to record the restart timing information when
configured with --enable-timing.
The issue was due to recent changes in the barrier API. The
new implementation would first check if the coordinator had
released all the requested global barriers, and if not, it would
execute a barrier and increment a counter that keeps track of
the number of executed barriers. However, the implementation
failed to stop and record the restart timer when the global
counter (or the number of executed barriers) became equal to
the number of requested global barriers.
> dmtcp_coordinator: Fix restart timing

- src/plugin/pid/pid_miscwrappers.cpp
This patch adds a EXTERNC to correctly compile the CMA wrappers
as C functions and also adds cases for CMA system calls in the
syscall() wrapper.
> pid_miscwrappers: Fix CMA wrappers

- src/plugin/ipc/file/fileconnection.cpp
Consider a scenario in which file was opened for writing and however
its got deleted in between prior to taking dmtcp checkpoint. fds are
still opened for process but file is actually deleted. This is not
handled and dmtcp checkpoint exit as it tries to checkpoint the deleted
file. This was handled in previous within handleUnlinked file function
but code was cleaned.
> Issue is occuring using --checkpoint-open-files for ckpting open files

- src/plugin/ipc/file/fileconnection.cpp
For files opened using the fopen* family of functions, the `_flags` field
of the `FileConnection` object is initialized to -1. The field is initialized
when the object is created at the time  of opening the file and is never
set to the correct value.
This patch fixes an issue caused because the `preCkpt()` method
incorrectly referred to the `_flags` field to determine how to save a
copy of an opened file (when using the `--checkpoint-open-files` option).
This fix is to use the `_fcntlFlags` field instead of the `_flags` field
in the `preCkpt()` method. The `_fnctlFlags` field is set to the value
returned by `fcntl(F_GETFL)` in the `drain()` method, which gets called
before `preCkpt()`.
> fileconnection: Fix preCkpt() for files opened using fopen-family

- src/plugin/ipc/file/fileconnection.cpp
When using the `--checkpoint-open-files` flag, on restart, the contents
of the saved version of a file are compared with its existing copy (if
any), and if the contents differ, DMTCP's policy is to throw an error to
the user. This is done to ensure that a user's file is not accidentally
overwritten. However, the existing implementation of the file comparison
function, `areFilesEqual()`, would assert out with a misleading error
message leaving the user confused when the file contents differed. This
patch forces the comparison function to return a comparison failed
(false) result to its caller to allow the caller to assert out with a
more meaningful error message.
> Expose file-contents-differ error msg to user when using ckpt-open-files

- src/plugin/ipc/file/fileconnection.cpp
This patch fixes an issue where DMTCP would incorrectly restore
files that were unlinked after opening with O_WRONLY.
The policy for checkpoint-restore of such files was first defined
in the commit 5c3dd0a as follows:
a) DMTCP should not checkpoint such files, regardless of the
--checkpoint-open-files flags; and
b) On restart, DMTCP should open such files with (O_WRONLY|O_CREAT)
and unlink them.
However, the implementaiton never achieved these goals. We did end up
doing the first part correctly, but never really got the second path right.
With the above commit, files would be opened with (O_WRONLY|O_CREAT)
on restart but were never unlinked because the commit overlooked an
if-clause in the `FileConnection::resume()` method. The if-clause would
call unlink() only if a file had the …
> fileconnection: Fix checkpointing of unlinked files opened with O_WRONLY

- src/plugin/ipc/socket/socketwrappers.cpp
This patch is an attempt to fix the issue of masking of the _real_
errno by DMTCP's socket wrappers.
The problem is that the code in a wrapper between the call to the real
function and the return statement, for example, JTRACE's, etc., can have
a side-effect of modifying the errno. As a result, the wrapper can end
up returning an incorrect errno to the user. The solution is to save
the errno once a real call returns and restore it just before returning.
Although this patch only addresses the issue for socketwrappers, the
problem is more widespread (see issue #365); I'm putting this out for
early feedback.
> socketwrappers: Fix masking of real errno

- src/constants.h
- src/dmtcp_coordinator.cpp
- src/dmtcp_launch.cpp
- src/dmtcp_restart.cpp
- src/restartscript.cpp
This patch adds a `--coord-logfile <filename>` option to dmtcp_coordinator,
dmtcp_launch, dmtcp_restart, and the restart script. This option can be
used to specify a file where the coordinator can dump its log messages
when running in daemon mode. This is useful for debugging.
> Add support for logging coordinator messages when running in daemon mode

- src/mtcp/mtcp_restart.c
In `mtcp_restart.c`, the function `mtcp_sys_brk()` can be called to set an earlier end-of-data.  In this case, the `brk()` kernel call will munmap the leftover memory.  But the `rinfo` struct can be stored near the end-of-data, which is then munmap'ed inside `restore_brk()`.  This fixes it by delaying the `brk()` call in this case, until later in `restorememoryareas()`, after we're done using the global struct, `rinfo`.
> Fix case when mtcp_sys_brk() causes munmap()

- src/ckptserializer.cpp
- src/restartscript.cpp
The existing implementation of the `open_ckpt_to_write()` passes a
NULL environment to the gzip child process. This can be an issue (#370) , as
reported by a user on Github (Github ID: MrPrezident), if gzip (the
real binary or a wrapper script around the real binary) relies on some
environment variables.
The fix here is to let the gzip process inherit the environment of the
parent process by using `execvp(gzip, gzip_args)` instead of `execve(gzip,
gzip_args, NULL)`. Note that the code in the function unsets LD_PRELOAD
for the child process already.
> ckptserializer: Fix passing a NULL environment to the gzip process

- src/plugin/ipc/file/fileconnection.cpp
This patch fixes an issue with ckpt-ing of deleted files caused when a plugin
uses the `dmtcp_must_ckpt_file()` API to force checkpointing of a
file that might have been deleted. The fix is to return early from the
`FileConnection::drain()` method in case of a deleted file, i.e., return
without checking for the return value of the `dmtcp_must_ckpt_file()` API.
> fileconnection: Fix ckpt-ing of deleted files

- include/dlsym_default.h
- include/dmtcp.h
- src/Makefile.am
- src/Makefile.in
- src/dmtcp_coordinator.cpp
- src/dmtcp_coordinator.h
- src/dmtcpmessagetypes.cpp
- src/dmtcpmessagetypes.h
- src/dmtcpworker.cpp
- src/dmtcpworker.h
- src/plugin/pid/pid.cpp
- src/plugin/pid/pid_miscwrappers.cpp
- src/plugin/pid/pid_mutexwrappers.cpp
- src/pluginmanager.cpp
- src/syscallsreal.c
- src/threadsync.cpp
- src/workerstate.cpp
- src/workerstate.h
The initialization is reorganized even further to handle bugs when an application with LD_PRELOAD library calls system() in one of its constructors.
> Bug fixes for b4dd323

- plugin/pathvirt/pathvirt.cpp
Assume that path virtualization is enabled and after restart, proces will
perform path virtualization. Now consider that restarted process connects
to some external process which is not running under DMTCP. On connection it
sends some path which was present in virtual->physical mapping. This would
be problem for external process as it would not perform path mapping.
This can be solved if restarted process can query for the physical mapping
and accordingly send the new path to external process.
PathVirt plugin already has same api but that is not exposed, can this API
be exposed similar to other DMTCP APIs.
> New API get_virtual_to_physical_path

- jalib/jalib.cpp
- jalib/jalib.h
- jalib/jsocket.cpp
- src/jalibinterface.cpp
This patch fixes an issue (#389) with the `monitorsockets()` function that
would result in a buffer overflow at checkpoint time for applications
that open many file descriptors (> 1024). The issue arises due to
the use of `select()` call.  The root cause for the buffer overflows
is the implementation of `FD_{SET|CLR|ISSET}` macros in glibc. However,
according to the man page, it's the application's responsibility to ensure
that these macros are not called for a file-descriptor that is larger than
FD_SETSIZE, which is typically 1024 in most implementations.
The fix here is to re-implement the function using `poll()`, which scales
better than `select()`.
> monitorSockets: Re-implement using poll()

- src/plugin/ipc/file/fileconnection.cpp
Consider a scenario in which file is already opened by
parent and now child process is forked. DMTCP infrastructure
doesn't populates _flags field in FileConnection class of
child process. Now at certain time file is deleted using
unlink however file pointer was not closed. Further
child process invokes the application level checkpoint.
This has resulted in issue. Fix is to use _fcntlFlags
filed
> File deleted bug 

- src/plugin/pid/pid.cpp
- src/plugin/pid/pid_syscallsreal.c
- src/plugin/pid/pidwrappers.h
This appears to be an old bug. Usage of close()/dup2() can lead
to unexpected consequences where a fd associated with a different
plugin (socket, etc.) may be closed affecting their behavior on
restart.
I noticed this issue when a raw socket associated with the IPC plugin
was being closed unintentionally as a result of calling close() in the
pid plugin's restart callback. The temporary PIDMAP fd opened in the
restart callback happened to be the same as the socket fd that the raw
socket was associated with prior to checkpointing.
> pid-plugin: Fix restart callback to use _real_* functions

- configure
- configure.ac
In commit 2590376dc (Sep. 16, 2015), I accidentally removed ARM (32-bit) support while trying to add AARCH64 support.  I've tested this restoration on a BeagleBoard (ARM Cortex A8), and it seems to be working there.
The only real change is in configure.ac.  You can see what I did by looking at my buggy commit:
`git diff 2590376dc^ 2590376dc -- configure.ac`
and comparing that old commit with the diff for configure.ac in this commit request.
I'm hoping for a fast review.  :-)  This should go into all of 3.0, 2.5, and 2.4.5.
> Fix commit 2590376dc (restoring ARM_HOST)

- src/plugin/ipc/socket/socketconnection.cpp
- src/plugin/ipc/socket/socketwrappers.h
The select() call is only capable of handling 1024 fds. Usage of select()
with more than 1024 fds can lead to undefined behavior because of the
way it's implemented in libc. This patch replaces a call to select()
with poll() in the drain() method of the TcpConnection class.
> socket-plugin: Replace call to select() in drain() with poll()

- src/mtcp/mtcp_restart.c
This should be an easy review.
First commit is a short fix for 32-bit DMTCP under Linux-2.6.18.  The 'vdso' segment is not annotated by the kernel, and a user needed DMTCP to work in this configuration.
The second commit is minor:  just changing formatting strings in `src/mtcp/mtcp_restart.c` for greater clarity.
> Fix mtcp_restart for 32-bit mode for Linux-2.6.18

- src/plugin/ipc/connectionlist.cpp
- src/plugin/ipc/file/ptyconnection.cpp
- src/plugin/ipc/ipc.h
- src/plugin/ipc/ssh/util_ssh.cpp
This patch is a follow-up to commit: 907003c. As mentioned before, the
select() call is only capable of handling 1024 fds. Usage of select()
with more than 1024 fds can lead to undefined behavior because of the
way it's implemented in libc. This patch replaces calls to select()
with poll() in four different places in the IPC plugin.
> ipc-plugin: Replace calls to select() with drain()

- src/plugin/pid/pid.cpp
The pid plugin uses the `mapMutexVirtTid` STL map to track mutexes used
by an application. This is required to patch the libc internal mutex
structs on restart. The problem with the current approach is that calls
to allocate and initiate the map (using the new operator) can lead to
a deadlock when an application defines uses a custom memory allocator
library that ends up calling other wrappers. The fix is to force the
allocation of the map from the DMTCP alloc arena.
Here's an excerpt from a stacktrace demonstrating the bug:
#15 pthread_mutex_lock ()
#16 dmtcp::ConnectionList::_lock_tbl ()
#17 dmtcp::ConnectionList::add ()
#18 dmtcp::FileConnList::processFileConnection ()
#19 _open_open64_work ()
#20 open (path=0x5809fc "/dev/zero", flags=<optimized out>)
...
#23 operator new (req=48)
#24 …
> pid-plugin: Use pre-allocated buffer for mutex map

- src/shareddata.cpp
- src/uniquepid.cpp
The current implementation for generating a unique computation
identifier relies on a low resolution timer function,
`time()`, with a min. resolution of 1 second. This can result in
conflicts in the computation id space when running independent
computations in parallel on the same host.
I first encountered this problem when launching independent
programs under DMTCP in parallel using `make -j`. I noticed
that a program would end up reading the coordinator info
from the shared data area of a different program because
of matching computation id values. The program would then
try to send messages to the wrong coordinator and result in
undefined behavior.
The fix is to use a higher resolution timer API, `clock_gettime()`,
with a min. resolution of 1 nanosecond.
> Uniquepid: Generate comp. id using higher resoulution timer

- jalib/jbuffer.cpp
- jalib/jbuffer.h
- src/plugin/ipc/socket/socketconnection.cpp
- src/plugin/ipc/socket/socketconnection.h
- src/plugin/ipc/socket/socketwrappers.cpp
This patch adds some basic support for raw (netlink) sockets with some
reorganization and clean-up of the code in the socket plugin.
Future patches will make the support more robust.
> socket-plugin: Add basic support for raw (netlink) sockets

- include/dlsym_default.h
- src/dlsym_default.c
The old DLSYM_DEFAULT implementation works exactly as expected
when given an actual handle for a library. However, potential
problems arose with the use of the RTLD_DEFAULT and RTLD_NEXT
pseudo-handles. In these cases, the function relied on calls
to dlopen and dlsym which could cause an infinite loop if called
before the complete initialization of libc.
This commit replaces the usage of dlopen and dlsym with dladdr1 which
simplifies the process greatly and should fix this problem.
> Fix dlsym_default to not rely on dlsym and dlopen [duplicate of PR #347]

- configure
- configure.ac
It's generating a bunch of errors on TravisCI which are not visible on
other compilers.
> Removed `--Werror` from configure.ac.

- plugin/pathvirt/pathvirt.cpp
The corner cases include empty paths, and paths that share the
same prefix do not match, e.g., /dir1 and /dir12
> pathvirt-plugin: Fix several corner cases.

- contrib/delayresume/delayresume.cpp
- include/util.h
- src/execwrappers.cpp
When user wants to do fork()/exec() between block checkpointing
and unblock resuming, user's program should not run under dmtcp.
> delayresume: allow fork()/exec() without dmtcp.

- src/mtcp/mtcp_check_vdso.ic
dmtcp restart code attempts to increase the stack limit max to the ARCH_MAX ie, 256 MB. This fails to succeed when dmtcp is run under PBS (mom). PBS sets the stack max to whatever the system ulimit max was at startup (ie, value of ulimit -s). If the ulimit -s was unlimited, then pbs_mom leaves it as unlimited and that is the only case when dmtcp restart code works (since it is then able to increase the stack max to 256 MB).
The code block where dmtcp attempts to set the stack max could be removed. It could simply inherit whatever the current max limits are from the environment. Attempting to set the stack max does not make much sense anyway, since if it was limited by the parent (to lower than 256 MB), the call will ALWAYS fail. And if it was not limited then its already large and dmtcp …
> Remove code that attempts to set stack max to 256 MB at restart

- src/mtcp/mtcp_restart.c
This patch fixes issue #342. I have tested this with ICC-16.0.3.
There were two issues:
- Missing definition for the memfence() function; and
- Incorrect offset for the restorememoryareas_fptr in the rinfo
struct.
The second bug was introduced in the commit: dec2c26 when new fields
were added to the rinfo struct.
> Fix mtcp_restart for Intel C compiler

- src/util_init.cpp
This is a duplicate of PR #460 (for DMTCP 3.0) and PR #464 (for DMTCP 2.5.0)
> Comment JLOG call, fails with --enable-debug (for version 2.4.6)

- src/util_init.cpp
This is a fix for df0fe3ff30109f16fa6e33915efab196f065b9c0 :
"fixup! Fix misc. issues pointed out by static analysis"
In changing a C string to a C++ string, code was created: `string host = NULL`.
This errors out when DMTCP is configured as --enable-m32.  It should be: `string host = ""`.
> C++: string host = NULL fails on 32-bit DMTCP

- src/plugin/ipc/file/fileconnection.cpp
- src/plugin/ipc/file/fileconnection.h
- src/plugin/ipc/file/fileconnlist.cpp
- src/plugin/ipc/file/fileconnlist.h
This patch adds an ability to the file plugin to dump the information
about the open files that DMTCP saved in the last checkpoint. The open
files for each process in a computation are saved in its own separate
subdirectory. In each of these subdirectories, DMTCP will now also
write a text file that has all the meta-data about the files saved in
the subdirectory. This file would follow the format described below and
would be overwritten on every checkpoint.
fd-info.txt:
filename1: /original/path/to/filename1
filename2: /original/path/to/filename2
filename3: /original/path/to/filename3
The file can be parsed easily by a program or manually.
> file-plugin: Dump info. about ckpted open files

- contrib/infiniband/ibv_internal.h
- contrib/infiniband/ibvctx.c
The original code assumes that for RC connections, two QPs are always connected, which is not true in certain cases (the bug was found in Manuel's cluster using Mvapich2 2.2).
> Fixed the case where two QPs are not connected.

- configure
- configure.ac
- include/dmtcp.h.in
- test/plugin/applic-delayed-ckpt/applic.c
- test/plugin/applic-delayed-ckpt/plugin-to-announce-events.c
- test/plugin/applic-initiated-ckpt/plugin-to-announce-events.c
- test/plugin/example-db/example-db.c
- test/plugin/example/example.c
- test/plugin/sleep1/sleep1.c
- test/plugin/sleep2/sleep2.c
User plugins in version 3.0 required `#include config.h`.  This was a problem for two reasons:
1.  It would seem weird to the user.  The reason is that the new interface was using PACKAGE_VERSION, a configure variable from autoconf.
2.  `config.h` was defining lots of macros like PACKAGE_VERSION in the user's namespace.  This is bad, since the user might have defined their own macro, PACKAGE_VERSION.
The solution was to rename `include/dmtcp.h` to `include/dmtcp.h.in`, to add to it
`#define DMTCP_PACKAGE_VERSION "@PACKAGE_VERSION@"`
and then modify `configure` and `configure.ac` to auto-generate `include/dmtcp.h`.
I tested this on 3.0.  I assume we don't need this for 2.5, since 2.5 doesn't use PACKAGE_VERSION or `config.h` for plugins.
> Plugins for DMTCP 3.0 don't require config.h now

- src/dmtcp_coordinator.cpp
The fourth argument to `getaddrinfo()`, `results`, is a linked-list that
is allocated when a call to `getaddrinfo()` succeeds. However, when the
call to the function fails, the linked-list remains unallocated and any
attempts to free the linked-list (using `freeaddrinfo()`) can result in
a segmentation fault. The patch ensures that the results linked-list is
freed up only after a successful allocation.
> dmtcp_coordinator: Fix a segfault when getaddrinfo() fails

- src/mtcp/mtcp_restart.c
Apparently, the second vvar page is not readable and so a memcpy()
results in a BUS error. This commit tries to hack through it by ignoring
the second vvar page.
This is a port of PR #469 from master to the 2.5 branch.
> VDSO fix for i386.

- include/util.h
- src/miscwrappers.cpp
- src/plugin/pid/pid_miscwrappers.cpp
- src/plugin/svipc/sysvipcwrappers.cpp
> Avoid recursive call to shmdt() wrapper (for master: 3.0)

- include/dmtcp_dlsym.h
- src/plugin/pid/pid.h
These are stray C constants that were not removed as part of PR #456 (and related PRs for 2.4 and 3.0 branches).  These constants are no longer used.
(n the case of the 2.4 branch, this should be pushed in only after PR #494 is pushed in.  This is the port of PR #456 to 2.4.7.)
> Remove DLSYM_DEFAULT/DLSYM_DEFAULT_DEBUG; not used

- NEWS
This now adds NEWS for 2.4.5, 2.4.6, and the upcoming 2.4.7.
@rohgarg, I've forgotten the details of the 'dlsym' changes needed to support recent glibc's.  (And which glibc version, approximately, broke things?)  Could you remind me of the details so that I can fix that part?  Right now, I just say:
> * Recent versions of GLIBC treated versioned symbols differently.
>  This release also handles recent GLIBC versions.
That's clearly not good enough.  Thanks for any help on this (and also on the note about the kernel bug fix for vDSO if necessary).
> Updated NEWS file

- src/constants.h
- src/coordinatorapi.cpp
- src/dmtcp_command.cpp
- src/dmtcp_coordinator.cpp
- src/dmtcp_launch.cpp
- src/dmtcp_restart.cpp
- src/restartscript.cpp
There are three commits.  It will be easier to review by reading one at a time:
1.  Warn on restart if coord already running prev comp
2.  If --coord-port unspecified, use --new-coordinator 
- Prev., if no coord mode specified, `--any-coordinator` was the default.
This could cause `--join-coordinator` to be invoked.
This caused unexpected behavior when the user was unaware of a curr. coord.
- Changing -`-join` to `--join-coordinator`, but still recognizing `--join` for now.
3.  Use macro:  7779 -> `STRINGIFY(DEFAULT_PORT)`
> Improve coordinator logic

- src/coordinatorapi.cpp
Apparently, we had missed this one. This only affects us when running with the `--no-coordinator` flag.
> fixup! C++: string host = NULL fails on 32-bit DMTCP

- src/dmtcp_coordinator.cpp
- src/uniquepid.cpp
An issue was observed where multiple parallel launches/restarts of independent computations on a single node would up using the incorrect shared-data files. The reason was that since a shared-data file's name is generated using the following tuple: _<hostid, virt. pid, coordinator timestamp>_, multiple independent coordinators would end up generating the same values when they were launched in parallel.
The fix is to use a nanosecond resolution timer for generating the coordinator timestamp. Although this doesn't fix the issue entirely, it does reduce the chances of two independently launched computations on a node mapping the same shared-data file.
> dmtcp_coordinator: Use higher resolution timer for coordTimeStamp

- include/dmtcp_dlsym.h
- src/plugin/pid/pid.h
This is a copy of PR #493 for the 3.0/master branch.
> Remove DLSYM_DEFAULT/DLSYM_DEFAULT_DEBUG; not used (for 3.0/master)

- src/mtcp/mtcp_restart.c
This commit only affects ARM CPUs.  I tested the print statement on an Intel CPU, and the print statement seems to work.
> ARM CPUs: warn on invoking delay loop on restart

- src/plugin/ipc/file/fileconnlist.cpp
> fileconnlist: Mark /proc/pid/environ as pre-existing fd

- src/coordinatorapi.cpp
- src/coordinatorapi.h
- src/threadlist.cpp
This solves the issue where on restart there is a larger open file
descriptor limit.
> Reset the coordinator socket on restart.

- test/autotest.py
Fix long-standing bug that appears when an autotest test fails.  (joint credit w/ @rohgarg)
> Fix autotest.py: new coord if old one fails

- jalib/jtimer.cpp
- jalib/jtimer.h
- src/barrierinfo.h
- src/dmtcpworker.cpp
- src/dmtcpworker.h
- src/mtcp/mtcp_header.h
- src/mtcp/mtcp_restart.c
- src/plugininfo.cpp
- src/pluginmanager.cpp
- src/pluginmanager.h
- src/threadinfo.h
- src/threadlist.cpp
- src/threadlist.h
This patch allows DMTCP to dump additional information about barrier overhead, ckpt read and write times when configured with the `--enable-timing` flag. Each process of the computation writes out this information in a separate `timings.*.csv` file.
> Enhance --enable-timing

- src/threadlist.cpp
* DMTCP_RESTART_PAUSE was designed to stop for debugging as soon as we entered libdmtcp from mtcp_restart.
* In commit 7ecf5f4a, it was mistakenly decided to handle all postRestart events of all plugins before allowing the user to debug.
> DMTCP_RESTART_PAUSE: Fixing bug in commit 7ecf5f4a

- include/dmtcp.h.in
- src/constants.h
- src/dmtcp_restart.cpp
- src/mtcp/mtcp_restart.c
- src/plugin/ipc/file/fileconnlist.cpp
- src/plugin/ipc/ssh/dmtcp_ssh.cpp
- src/plugin/ipc/ssh/dmtcp_sshd.cpp
- src/plugin/pid/pidwrappers.cpp
- src/threadsync.cpp
On failure due to DMTCP, use: exit(DMTCP_FAIL_RC)
* There is a tendency to use 'exit(1)'.  But then the end user doesn't
know whether the target application failed or DMTCP itself failed.
Please check my logic carefully.  There are cases where we really did want `exit(0)`.  Also, where the code says something linke `exit(status)`, I did not attempt to change that.  And for `dmtcp_coordinator`, and `dmtcp_command`, I did not change things since the end user will not be confused by application failure versus DMTCP failure.
====
I added a small second commit, rather than create a separate pull request:
For the second commit to remove compiler warnings, I still have one compiler warning:
> dmtcp_restart.cpp:462:36: warning: deprecated conversion from string constant to ‘char*’ …
> The call to exit(1) should call exit(DMTCP_FAIL_RC)

- src/mtcp/mtcp_restart.c
The brk call fails on Debian for bash because of alignment conflict
between heap and mtcp_restart.
> mtcp_restart: Remove assert introduced in 72df6746

- src/coordinatorapi.cpp
- src/coordinatorapi.h
- src/dmtcp_command.cpp
- src/dmtcp_launch.cpp
- src/dmtcp_restart.cpp
- src/dmtcpplugin.cpp
- src/dmtcpworker.cpp
- src/execwrappers.cpp
- src/plugininfo.cpp
- src/pluginmanager.cpp
Instead of using a singleton class, we use the namespace with a couple of file-global variables (coordinatorSocket and nsSocket).
This PR is motivated by the interactions around instantiation of CoordinatorAPI singleton class during startup. Often, this has caused some weird code paths where the object instantiation calls malloc which in turn calls other functions/wrappers and so on.
> Replaced CoordinatorAPI class with namespace.

- jalib/jassert.cpp
- jalib/jfilesystem.cpp
- src/dmtcpworker.cpp
This fixes issue #537. Apparently, on older libc/libstdc++, the library
acquires a low-level lock in its constructor. This can lead to a deadlock
when the library, in its constructor, ends up calling a DMTCP wrapper,
which then calls other helper functions that have their own static
local objects that need to acquire the same lock to be initialized.
Here's a sample stacktrace:
__lll_lock_wait_private () from /lib64/libc.so.6
_L_lock_16 () from /lib64/libc.so.6
__new_exitfn () from /lib64/libc.so.6
__cxa_atexit_internal () from /lib64/libc.so.6
theLogFilePath () at ../jalib/jassert.cpp:171
jassert_internal::set_log_file ()
dmtcp::Util::initializeLogFile ()
prepareLogAndProcessdDataFromSerialFile () at dmtcpworker.cpp:231
dmtcp_initialize () at dmtcpworker.cpp:266
calloc (nmemb=1, …
> Eliminate static C++ objects from jassert, jfilesystem, and dmtcpworker

- include/shareddata.h
- src/shareddata.cpp
The `pthread_barrier` abstraction cannot be used with mixed 32-/64- bit
binaries due to the differences in the underlying `pthread_barrier_t`
structure.
We also implement a barrier using FUTEX_{WAIT,WAKE} mechanism along with
file-locking. It can be optimized further by using atomic built-ins.
The futex mode is automatically activated if running in mixed-mode,
otherwise, we use pthread_barrier abstraction.
> Re-implement local barriers using futexes for multi-arch mode.

- contrib/infiniband/ibv_internal.h
- contrib/infiniband/ibvctx.c
If a cq is associated with a completion channel, recreate the cq with the completion channel on restart.
> IB: create cq with completion channel on restart.

- src/execwrappers.cpp
This should be a temp fix. In the long term, we need to think about
how to inject new env vars for applications that have private copy
of env vars.
> pathvirt: patch new prefix env var before execve().

- src/dmtcpworker.cpp
- src/execwrappers.cpp
ThreadList::resetOnFork calls pthread_create which in turn calls
malloc/calloc, etc. This can result in a deadlock if the parent process
was holding malloc-lock while forking and might reset the lock only
during atfork_child handler. Because our own atfork_child handler is
called at the very beginning, the parent process won't have a chance to
reset the lock. Calling ThreadList::resetOnFork here ensures that any
such locks would have been reset by the caller and hence it's safe to
call pthread_creat at this point.
> Delay ckpt-thread initialization during fork.

- src/dmtcp_restart.cpp
- src/mtcp/mtcp_header.h
- src/mtcp/mtcp_restart.c
- src/threadlist.cpp
- src/threadlist.h
__This version of PR #512 is for DMTCP 2.5.1.  This PR for 2.5.1 was already reviewed there.__
> * Workflow:
env DMTCP_RESTART_PAUSE0=1 dmtcp_restart ckpt_*.dmtcp &
gdb PROGRAM_NAME PID
NOTES:
* This includes postRestartDebug() as target from mtcp_restart,
where postRestartDebug() has the infinite loop.
* In commit a8cfd6666, we removed '-g' as default.  It should be added back
in this commit, before this new commit.
> DMTCP_RESTART_PAUSE0 (for version 2.5.1)

- include/dmtcp_dlsym.h
- src/Makefile.am
- src/Makefile.in
- src/dmtcp_dlsym.cpp
- src/dmtcp_restart.cpp
- src/processinfo.cpp
- src/processinfo.h
We now warn the user if the vDSO layouts on the restart machine and the checkpoint machine are incompatible.
> Better handling of vDSO

- src/dmtcp_restart.cpp
- src/mtcp/mtcp_header.h
- src/mtcp/mtcp_restart.c
- src/terminal.cpp
- src/threadlist.cpp
- src/threadlist.h
- src/util_exec.cpp
__I've tested this and it works now.  Please review.__
* Workflow:
>    env DMTCP_RESTART_PAUSE0=1 dmtcp_restart ckpt_*.dmtcp &
gdb PROGRAM_NAME PID
NOTES:
* This includes postRestartDebug() as target from mtcp_restart,
where postRestartDebug() has the infinite loop.
* In commit a8cfd6666, we had removed '-g' as default.  I added a print statement with the `gdb attach` advice that reminds the user to configure DMTCP with `--enable-debug
> DMTCP_RESTART_PAUSE=[1234] (for version 3.0)

- contrib/infiniband/ibvctx.c
The error message when compiled with LLVM before the commit:
./keys.ic:17:6: error: conflicting types for 'sge_update_lkey'
void sge_update_lkey(struct ibv_sge * list, int len)
^
./ibv_wr_ops_recv.ic:7:3: note: previous implicit declaration is here
sge_update_lkey(wr->sg_list, wr->num_sge);
^
> Make it compilable with LLVM

- src/dmtcp_dlsym.cpp
The commit: 3dff1b3 added a warning for the user that would be triggered
when the checkpoint and the restart machines had incompatible vDSO
layouts. The warning was added as a nice-to-have feature where earlier the
restart would have just crashed without a clue. The code would determine
the layout using a minor extension to the `dmtcp_dlsym` function.
However, the current implementation would lead to a crash if the vDSO
section was not listed as part of the link_map. We have now observed this
issue on two separate systems -- a user reported this in issue #566 and
@jiajuncao separately observed this on a CentOS 7.2 system. This patch
fixes this problem by ensuring that `dmtcp_dlsym` doesn't crash in the
corner cases.
> dmtcp_dlsym: Fix a crash when link_map doesn't contain vDSO entry

- plugin/batch-queue/rm_main.cpp
- plugin/batch-queue/rm_pmi.cpp
- plugin/batch-queue/rm_utils.cpp
1. Redirect `PMI_Init()` to our wrapper, if the pmi library is opened by `dlopen()`.
2. Remove the pmi socket as a stale connection.
> Fix PMI issues

- src/dmtcp_restart.cpp
The help message says that with "-j" flag, dmtcp_restart tries to join
to default port. In fact it fails to do so, unless the port is
specified.
The commit fixes this bug.
> [BUGFIX] dmtcp_restart ignores -j flag if there no -p flag

- src/restartscript.cpp
When the coordinator is used with `--ckptdir` option (in more general way, when the coordinator's working directory and checkpoint directory are not the same), DMTCP should store the symlink next the newly created ckpt file. To do that, the `unlink` call should be called with an absolute pathname to dmtcp_restart_script.sh. 
This pattern was discovered when running two successive run in the same directory, the ckpt directory being changed through `dmtcp_set_coord_ckptdir()` API call. During the second run, the `unlink` failed because DMTCP is looking for a script located in coordinator CWD, but the script is not there. Then, the `symlinkat` failed because a symlink already exists.
This fix simply prepends the dirname to `filename`.
Feel free to modify if necessary.
> Fix bad restart_script.sh location when --ckptdir is used

- test/autotest.py
For 2.5, it's best to turn off the autotest for 'screen' until some time in the future when we fix it.  (Or we may choose to fix it only for the 3.0 master branch.)
> screen test is failing due to bad pty; skip test

- plugin/pathvirt/pathvirt.cpp
- src/util_misc.cpp
> Remove gcc warning in util_misc.cpp and pathvirt.cpp for 2.5 branch

- test/autotest.py
This should be an easy one to review, and it is blocking the Traivs tests until this is pushed in.
* Apparently, Travis added the 'screen' package recently.  Previously, this test was skipped.
* Maybe this will work after new pty plugin PR is added.
* We should review whether to include this test when the pty PR is added,
and make depend on HAS_RECENT_PTY that will be set in 'configure'.
> In autotest.py, DMTCP is failing on the screen test.

- test/readline.c
GNU Readline Library -> Programming with GNU Readline
https://cnswww.cns.cwru.edu/php/chet/readline/readline.html 
The order of the includes failed on the Fedora and the new order of the include files is consistent with the GNU manual.
> change the include file order for Fedora

- src/dmtcp_launch.cpp
This is a port of changes from a recent commit: 8085468 for `dmtcp_restart` to `dmtcp_launch`.
> dmtcp_launch: Fix the behavior of -j when -p is not specified

- src/plugin/ipc/file/fileconnection.cpp
This bug appears to have crept in as part of commit: 804246e63, where
the method `FileConnection::handleUnlinkedFiles()` was removed and its
code was merged into the `FileConnection::drain()` method.
> fileconnection: Correctly handle deleted files on NFS

- src/plugin/pid/pid.cpp
- test/sched_test.c
This fixes issue #203 (and possibly even #605).
> pid-plugin: Save and restore CPU affinities for threads

- src/util_misc.cpp
This was discovered in CentOS 6.8 and 6.9.
> Added NSCD area for CentOS.

- src/plugin/pid/pid.cpp
Apparently, on some old distros, the code fails to compile without this
include file. *ALSO, which is commit 30c03f23 ?  I don't find it anywhere.  Is there a corresponding PR?*
> pid: Fix an error introduced in 30c03f23

- src/dmtcp_restart.cpp
Even when compiled with the logs enabled, the logs weren't getting written
out to the log file(s) in the tmp directory. The issue was that the log file
was never opened correctly for writing.  This patch fixes this issue.
> dmtcp_restart: Fix a bug with debug logging

- src/threadlist.cpp
A bug was observed where a newly-created thread post restart would end
up reusing the TLS of a thread that existed pre-checkpoint. Libpthread
decides to recycle the old TLS, and as an optimization, would not
update the pid field in the thread-block (under the assumption that
the pid never changes). Consequently, calls to pthread_cancel(), etc.,
for the newly-created thread would end up calling system calls (tgkill,
etc.) with the wrong pid and fail.
The fix is to call `TLSInfo_UpdatePid()` for any new thread in the
`clone_start()` function, which is the first thing the new thread
executes.
> threadwrappers: Fix pid in TLS of newly-created threads

- src/dmtcp_coordinator.cpp
- src/plugin/ipc/ssh/ssh.cpp
There are now two commits.
**FIRST COMMIT:**
dmtcp_coordinator.cpp was giving a warning:  `Failed to find coordinator IP address.`, and then not setting the IP address of the coordinator.  This forced the clients to use the original hostname.
The issue is that we use `gethostname()` to get the hostname, and then `getaddrinfo()` to get the IP address, and then `getnameinfo()` to get the name again.  When name and hostname didn't match (even though they have the same IP address), we refused to set the IP address and issued a warning.
In recent distros, it's common for the same IP address to have two hostname aliases.  So, now we use `gethostname()` as the hostname, and the common IP address is used.
The same patch is applied both to `dmtcp_coordinator.cpp` and to …
> Elim bad warning: Failed to find coord IP address.

- src/util_init.cpp
If ```host``` is another local variable, we have the use-after-free risk.
> Change _cachedHost to a string object.

- test/autotest.py
That had several tests failing on very loaded machines, that used legacy GZIP values
1. shm2 test: failed due to previous test frisbee not restoring GZIP value to pre-test value
2. bash & tcsh tests: now using GZIP enabled, to speed up the tests
> Fixed testing script

- test/dmtcp2.c
- test/dmtcp3.c
- test/file1.c
- test/file2.c
- test/openmp-1.c
- test/pthread2.c
- test/pthread4.c
The file tests were filling up the disk space at an alarming rate
especially when coupled with --slow and caused CI tests to fail if the
test box had lower disk space.
Similarly, reduced the frequency of unwanted printfs from some test
cases to allow for better debugging with manual launches.
> Reduced verbosity of several test programs.

- src/plugin/ipc/file/fileconnection.cpp
The vector `_in_data` was using the incorrect serialization
primitive. This would cause problems when forking a 32-bit process from
a 64-bit process. Thanks to R Balaji for catching this bug and the fix.
> fifoconnection: Fix serialization of vector

- src/mtcp/restore_libc.c
Now covers distros with glibc 2.24-NNN.
> Fixes for glibc >=24. Enhances 250a962.

- src/glibcsystem.cpp
When the child process crashes (for example, with a SEGFAULT), the
system wrapper should return with -1. However, in our case, we'd get
stuck in an infinite loop because the waitpid call would return -1. This
behavior of waitpid is expected [1], and our code wasn't checking for
this behavior correctly.
[1] Acc. to the waitpid man page, this can happen "for one's own child
if the action for SIGCHLD is set to SIG_IGN." Note that we do set SIG_IGN
as the action for SIGCHILD at the start of the `do_system()` function.
> Fix deadlock in system() wrapper when the child crashes

- configure
- configure.ac
- src/plugin/ipc/connection.cpp
This should be easy to review.  he PR has two tiny commits to fix bugs.
Now, `bin/dmtcp_launch -i 5 test/dmtcp1` works, as well as several other random tests by hand.  But for some reason, `make check` is failing.  When running `python autotest.py -v dmtcp1`, it seems to show some problems with `fcntl` and `F_SETOWN`.  But we can leave for another day digging into this remaining mystery.
> WSL fix: now mostly works if not using 'make check'

- src/mtcp/mtcp_restart.c
`mtcp_sys_brk()` is an inline assembly call. It returns the kernel return
value on success, and -1 on failure. Note that the kernel, unlike the
glibc `brk()` wrapper, returns the new program break on success, and
the current program break on failure.
> mtcp_restart: Correctly check return value of mtcp_sys_brk()

- src/threadsync.cpp
We need to reset the `preResumeThreadCount` in the child process in the
atfork_child handler. Otherwise, if a process is forked in the resume
phase, this can lead to a deadlock, where the checkpoint thread that's
created for the child process in the fork() wrapper gets blocked in
waitForUserThreadsToFinishPreResumeCB(). This is because the child process
inherits the non-zero value of `preResumeThreadCount` from the parent.
> Fix deadlock when a process is forked in the resume phase

- src/dmtcp_launch.cpp
- src/membarrier.h
- src/mtcp/mtcp_restart.c
- src/mtcp/mtcp_sys.h
Should be easy to review.  The essential changes are all in the file `src/mtcp/mtcp_restart.c`.  I removed the delay loop for __aarch64__, and added different code.  The issue is that when we mmap and copy new code into it, this is _self-modifying code_.  On the ARM and ARM64 CPUs, that operation requires the program to invalidate the previous cache conctents.  Otherwise, one waits for the cache to catch up, or one observes an ILLEGAL INSTRUCTION error.
Beyond this, one needs a data and instruction barrier, so that all instructions complete and no prefetches are attempted when switching to the new memory region.
Linux/gcc/glibc don't really provide a clean way to invalidate the cache.  So, I added somewhat hackish code with clear comments about what the issues are.
> Fix for aarch64, no delay loop on restart

- src/dmtcp_coordinator.cpp
- src/plugin/ipc/ssh/ssh.cpp
Applications which launch processes on remote machine won't be able to run under DMTCP due to
incorrect evaluation of host IP as well as coordinator IP. Problem is localhostIPAddr structure
is empty and code breaks the loop without doing a memcpy.
> Fix: Coordinator/Host IP is incorrectly calculated

- src/mtcp/mtcp_restart.c
- src/processinfo.cpp
This fixes the problem we've been seeing on modern libc/gcc versions where mtcp_restart has additional readonly-data sections that must be copies to the restore location. 
Instead of doing a memcpy which required invalidating the icache on certain ARM cpus, this patch now uses mmap to map the text/data regions at the restore address. The hope is that  we won't need to patch icache since the kernel/cpu would see the newly mmapped region as regular text.
Another change in PR copies the contents of the original mtcp_restart stack to the "safe" restore location. Next, we calculate the offset between the original stack location and the restore stack location.  This offset is then added to the stack pointer ($rsp) and framepointer ($rbp/$fp) registers. That way, we can continue to use the …
> Updated remapping of mtcp_restart and stack.

- include/trampolines.h
Currently, the code set the page permission to 'rwx' where the
trampoline needs to be set up. This is required as we write a few
bytes to the memory to set the trampoline. However, the code
segfaults if the number of bytes that need to be written reaches the
boundary of the current page and tries to write onto a next read-only page.
This patch would fix the edge case by providing `rwx` permission to
the next page if required.
> fix trampoline setup code for an edge case

- jalib/jsocket.cpp
We do a JASSERT before memcpy() to ensure that the size_t, `n`, is not too large.  But the gcc-7 compiler with `-Wall` doesn't recognize our JASSERT(), and thinks that `n` could be too large.  So, we add an 'if' condition to satisfy `gcc-7 -Wall`.
This is a two-line change, plus a one-line comment: easy to review.
> Add 'if' cond to memcpy(), to stop gcc-7 warning

- src/mtcp/restore_libc.h
The key is to read `man snprintf` carefully for what shoudl be the return value.  snprintf returns the number of characters that _would_ have been written (not counting the final null character).  This return value, `rc`, may be larger than the parameter `n` (max size to be printed), and the user must test `if (rc >n) ...`.  The original code assumed that snprintf returned the actual number of characters (i.e., `rc<=n`), which is not correct.
This bug was exposed using gcc-7.x, which issues a warning for this.
@karya0, by the way, `git blame` seems to indicate that the original code was yours -- but back in your younger years.  :-)
> Bug fix for commit 18e0aa04 (bad use of snprintf)

- src/dmtcp_launch.cpp
Easy review: one-line bug fix
Without this, the env. var. `DMTCP_HIJACK_LIBS` has extra ':' delimiters (mostly harmless), and `DMTCP_HIJACK_LIBS_M32` is missing its ':' delimiters (very harmful for 32-bit applications).
> Fix LD_PRELOAD and LD_PRELOAD_M32 env vars

- src/plugin/ipc/ipc.cpp
This PR provides an obvious one-line fix.  Please review this quickly.
This bug was reported by Pankaj Mehta at Synopsys.
> Fix return value of dup2 wrapper in ipc plugin

- src/plugin/ipc/ipc.cpp
- src/writeckpt.cpp
The commit only changes two or three lines of code.  But please see the comment that explains why this commit is important.  It can occur on a second restart after a first checkppoint, and was observed directly in RHEL 6.6.
This bug fix was contributed by:
1) Johannes Stoelp
2) Laurent Buchard
3) Pankaj Mehta
from: Synopsys, Inc.
> Second restart fails if vdso conflict w/ user data

- src/Makefile.am
- src/Makefile.in
- src/plugin/ipc/ipc.cpp
- src/pluginmanager.cpp
- src/processinfo.cpp
- src/processinfo.h
- src/rlimitfloatenv.cpp
- src/writeckpt.cpp
- test/autotest.py
- test/rlimit-restore.c
Continuation of PR #746.  Stupid github has Travis using an incompatible 'java' and 'javac' versions for an obscure reason.  It one does a sanity test to see if an earlier version would pass the Travis test, then github decides to close the pull request because it sees that the most recent push has 0 new commits -- even though no one told it to close the PR.
Let's continue the discussion here, that was started in PR #746.
This version of the PR now adds a third commit to fix Travis's incompatible java vs. javac versions in the presence of Python (see below).
> Restore floating point env and RLIMIT_NOFILE/STACK (v2)

- include/shareddata.h
- src/shareddata.cpp
@rohgarg observed with g++-9.1 that the attribute ` __attribute__((packed))` in shareddata.h causes many warnings and an error:  @karya0 had already developed this commit to solve the problem (as one of two commits in PR #747; but the otehr commit is unrelated to this).  PR #747 was not passing Travis anyway.  This PR isolates this comit as a separate PR.
> SharedData: fixed header packing and member sizes.

- test/Makefile.in
- test/autotest.py
- test/plugin-init.cpp
This test is added to both the master/3.0 and the 2.6 branches.  (See the next PR for details.)
In addition, the 2.6 branch was failing this test, and an additional commit will be added to the 2.6 branch to fix this., in the next PR.
> test/plugin-init: INIT event before libc init'ed

- jalib/jalib.cpp
- src/miscwrappers.cpp
- src/nosyscallsreal.c
- src/syscallsreal.c
- src/syscallwrappers.h
- test/autotest.py
- test/rlimit-nofile.c
* The commit now checks for a static protected fd base less than 1024,
and triggers assert during init/exec/restart if the current
RLIMIT_NOFILE will not leave enough fd's for the protected fd's.
* The commit adds a wrapper around setrlimit, to refuse to reduce
RLIMIT_NO below 1024.
* In the second commit, an autotest was added to check if the user lowered RLIMIT_NOFILE,
but not below 1024.  This test should pass.
> Lowering RLIMIT_NOFILE can cause crash

- src/plugin/pid/pid_mutexwrappers.cpp
- test/autotest.py
Enhancement to support mutex owner and robust mutex.  Note that these will be supported only with `./configure --enable-mutex-wrappers`.  The `--enable-mutex-wrappers` flag is not the default since it can add some runtime overhead if mutex operations are used very frequently.
With this patch, the `pthread3` test stops working, although the `mutex*` tests are added and do work.  This is a good tradeoff, in order to capture the new features.  I will creating an issue (issue #749) to record that the `pthread3` test fails with this configure option (at least for CentOS 7.5).
This bug fix was contributed by:
1) Johannes Stoelp
2) Laurent Buchard
3) Pankaj Mehta
from: Synopsys, Inc.
> Record mutex owner, and handle robust mutexes

- src/dmtcp_dlsym.cpp
* get_dt_tags() sees relative addresses for tags in linux-vdso.so.
These must be converted to absolute addresses.
In version 3.0 (master), the previous code worked only if linux-vdso.so was at highest address.
This commit is more robust.  It explicitly checks for linux-vdso.so,
since this is the only library using relative addresses.
For some reason, the original bug fix by @rohgarg was never pushed into the 2.x (now 2.6) branch.
The commit only changes two or three lines of code. But please see the comment that explains why this commit is important. It can occur on a second restart after a first checkppoint, and was observed directly in RHEL 6.6.
This bug fix was contributed by:
1) Johannes Stoelp
2) Laurent Buchard
3) Pankaj Mehta
from: Synopsys, Inc.
> Fix dmtcp_dlvsym (handling of versioned symbols)

- src/dmtcp_coordinator.cpp
This is necessary when one wants to use the publish/subscribe service before checkpoint, and throughout checkpoint and resume.
> Do not reset the NS (publish-subscribe) database on checkpoint/resume.

- test/syscall-tester.c
test/syscall-tester failed when run as root (even without DMTCP).   It's because the syscall-tester wanted to guarantee that some mknod tests fail when run as non-root, and we were succeeding.  So, we didn't pass the test.
This fix is important, since a Debian build does these tests as root.  We need this for the Debian package.
This should be an easy review.
> Fix test/syscall-tester; This test fails under root

- util/gdbinit-example
This adds the file `gdbinit-example` to the util directory.  It is there as an example of debugging DMTCP.  It can easily be modified by the end user.
This should be an easy review.
> Add gdbinit-example to util dir

- src/dmtcp_coordinator.cpp
This is a port of PR #632 from the 2.6 branch to the master/3.0 branch.
@karya0, could you review this one-line change?  Thanks.  The intention is to avoid resetting the lookup service during a checkpoint/resume.  We do it only during a restart.  (This is what PR #632 was doing.)
The original commit was by @jiajuncao, for the sake of the InfiniBand plugin.  We are now committing his InfiniBand plugin into 3.0/master.
> Do not reset the NS database on checkpoint/resume (for 3.0)

- src/shareddata.cpp
This is a continuation of PR #722.  See that PR for the details.  Since @rohgarg was unavailable to rebase, and then push in the PR, I'm doing it here, while maintaining a commit with his signature.
> shareddata: Fix a race when multiple clients join simultaneously

- test/plugin/README
- test/plugin/applic-delayed-ckpt/Makefile
- test/plugin/applic-initiated-ckpt/Makefile
Easy to review.
Removing unnecessary `-ldl` in Makefile of `applic-initiated-ckpt` and `applic-delayed-ckpt`
(Now that we use our own `dmtcp_get_libc_dlsym_addr()`, we don't depend on libc `dlsym()`.)
Adding missing description in `test/plugin/README`.
> Polishing test/plugin: README, Makefile

- src/plugin/svipc/sysvipc.cpp
- src/plugin/svipc/sysvipc.h
Resume refill barrier for sysvipc plugin never called, because refill
function always immediately returns, when isRestart is not true.
> Remove meaningless barrier

- jalib/jalib.cpp
- jalib/jalib.h
- jalib/jalloc.cpp
- jalib/jsocket.cpp
- src/jalibinterface.cpp
- src/miscwrappers.cpp
- src/nosyscallsreal.c
- src/syscallsreal.c
- src/syscallwrappers.h
- src/util_misc.cpp
This is just a cleanup of some code leftover from the FReD era. These wrappers (and the corresponding _real_ functions aren't needed anymore).
> Removed some unused wrappers from DMTCP.

- src/mtcp/Makefile.debug
- src/mtcp/Makefile.in
This flag is not needed as we now mmap the mtcp_restart regions instead
of doing memcpy. The code automatically emits the proper address for the
add-symbol-file command.
> Removed --text-offset from MTCP makefiles.

- include/dmtcp.h
- src/coordinatorapi.cpp
- src/dmtcp_coordinator.cpp
- src/plugin/ipc/connection.cpp
- test/autotest.py
- test/presuspend.c
This PR adds a test that exercises the `presuspend` barrier path and kills a child process. This is similar to our original use-case of killing auxiliary processes during the presuspend phase.
> Presuspend test and bugfixes.

- src/restartscript.cpp
This is an easy review.  In dmtcp_restart_script.sh, we test for `dmtcp_discover_rm` in path by doing `which dmtcp_discover_rm`.  We should send stderr to `/dev/null` when the `which` fails, rather than print to user's terminal.
> restartscript: 'which dmtcp_discover_rm 2>/dev/null'

- src/coordinatorapi.cpp
This is a continuation of PR #728.  See that PR for the details. Since @rohgarg was unavailable to rebase, and then push in the PR, I'm doing it here, while maintaining a commit with his signature.)
> coordinator-api: Fix caching of coordinator host info

- src/mtcp/mtcp_restart.c
- src/plugin/ipc/connection.cpp
Windows build 1903 doesn't yet support MAP_GROWSDOWN.  Also, Windows-1903 doesn't support fcntl on pipes, and so 'make check' fails when it tries to use pipes for the test.
This is an incomplete fix that I had written about having ready a few weeks ago.  But I had wanted to do debugging including in src/mtcp_restart, before committing my PR.  Debugging in src/mtcp was made possible again only six days ago, with PR #772 .
> Windows WSL: fix 'make check'

- include/dmtcp.h
- test/plugin/applic-delayed-ckpt/Makefile
- test/plugin/applic-initiated-ckpt/Makefile
- test/plugin/example-db/Makefile
- test/plugin/example/Makefile
- test/plugin/sleep1/Makefile
- test/plugin/sleep2/Makefile
Right now, a user (like me) will copy a plugin from test/plugin into their own directory.  They will then coyp `include/dmtcp.h` into that plugin directory and adjust `Makefile~, so ~DMTCP_INCLUDE=.`.  They will then do `make` to make binaries from the source.
This doesn't work because their is a hidden file, `include/dmtcp/version.h`, that is included through `include/dmtcp.h`.
So, the plugin API should not change with newer 3.x DMTCP versions (or at least not change too much).  But the user is not allowed to copy their plugin tarball to a new machine, with their built-in `dmtcp.h`, and compile and run using a public DMTCP executable in their path.  They also have a dependency on `/usr/include/dmtcp/version.h` (or `/usr/local/include/dmtcp/version.h` or some other location that they need …
> Make plugin source independent of dmtcp/version.h

- src/dmtcp_coordinator.cpp
- src/dmtcp_coordinator.h
The ckpt timer should be re-armed _after_ the previous checkpoint has completed.
> Fixed interval timing when ckpt takes longer than the interval.

- plugin/batch-queue/rm_main.cpp
- plugin/modify-env/modify-env.c
- plugin/unique-ckpt/unique-ckpt.cpp
- src/plugin/ipc/connection.cpp
- src/plugin/ipc/event/eventconnlist.cpp
- src/plugin/ipc/file/fileconnlist.cpp
- src/plugin/ipc/file/ptyconnlist.cpp
- src/plugin/ipc/socket/socketconnlist.cpp
- src/plugin/ipc/ssh/ssh.cpp
- src/terminal.cpp
`./configure --enable-debug` invokes `gcc -Wall', which implies `gcc -Wswitch`.  We then get spurious warnings unless we add a default case:
```
default:  // other events are not registered
break;
```
> Add 'default:' to 'switch' for: gcc -Wswitch/-Wall

- test/autotest.py
This modification of `autotest.py` now allows it to run under both Python3 and Python2.6/2.7.
The autotest.py file was already using `#!/usr/bin/env python`.  So, this modification fixes a bug on those systems where the default python executable is python3.  Also, given that Python is stopping support for 2.x as of Jan. 1, 2020, Debian is now rejecting packages that don't support Python3.
> Fix autotest.py for both Python3 and Python2.6/2.7

- src/signalwrappers.cpp
- src/threadwrappers.cpp
- test/autotest.py
The only part really to review is the two print statements in autotest.py.  Everything, else isjust  polishing comments.
In PR #792, I tested `python3 autotest.py` and `print #newline` had to be changed to `print()`.  But then, I didn't notice that in testing `python autotest.py`, this will print `()`.  So, now I use `printFixed("\n")` to do the same thing with both Python2 and Python3.
> autotest.py:  fix print bug in commit 7e00e93

- test/autotest.py
commit 7e00e93 extended autotest.py to support both Python and Python-3.
If fails with 'python3' for the test syscall-tester.  Apparently, travis uses Python-2.7, and so this bug with Python-3 wasn't caught.
This bug fix is easy to review (just one line: convert general string to ASCII string using `b'xc'` notation for `xc`.
> autotest.py: fix commit 7e00e93 for syscall-tester

- src/util_exec.cpp
This fixes compiler warning from g++-9.2 in `src/util_exec.cpp`.
There were two types of warnings (see the file diff):
1.  `strncpy(...)` complains about not copying the 'NUL' byte of string, even though the next line inserts `'\0'`.  So, I replaced `strncpy()' by `memcpy()`.
2.  `dmtcpArgs`, `numDmtcpArgs`, and `dmtcpArgBuf` are no longer used.  (Apparently, they were last added or modified in 2017.)
> Fix g++-9.2 compiler warnings in src/util_exec.cpp

- test/autotest.py
If you try `make -j check`, you'll now see:
```
== Tests ==
dmtcp1         ckpt:PASSED; rstr:PASSED -> ckpt:PASSED; rstr:PASSED
dmtcp2         ckpt:PASSED; rstr:PASSED -> ckpt:PASSED; rstr:PASSED
...
```
So, ';' means end of last process and starting a new process.  And '->' means continuation of current process.  This seems more intuitive for new users.
> More intutitive autotest format;  ';' = new process

- contrib/python/autocount.py
- contrib/python/counter.py
- contrib/python/dmtcp.py
- contrib/python/hookexample.py
- plugin/modify-env/modify-env.py
- plugin/pathvirt/test/slot5/pv-test.py
- util/dmtcp-style.py
- util/dmtcp_backtrace.py
- util/gdb-add-libdmtcp-symbol-file.py
- util/gdb.py
The PR title says it all.  The test/autotest.py was already made compatible with Python3 in PR #792.  Now, this PR provides the same treatment to the many other Python scripts in DMTCP.
> Accept Python3 or Python2 for all python scripts

- contrib/ckpttimer/ckpttimer.cpp
- jalib/jsocket.cpp
This is easy to review.  (Just two lines changed.)
- @JainTwinkle caught the bug in the contrib/ckpttimer plugin.  (Thanks.)
(contrib/ckpttimer exists only in master (version 3.0), not in version 2.x)
(Fix in commit d67aac7b for PR #773)
- 'bzero' is deprecated in favor of 'memset'
> Fix commit d67aac7b (contrib/ckpttimer plugin); and bzero in jsocket.cpp -> memset

- jalib/jalloc.cpp
In `jalib/jalloc.c`, `size_t _blockSize;` was not initialized to 0.
This one-line bug fix initializes it to `0`.  This should be easy to review.
> jalib/jalloc.c: 'size_t _blockSize;' wasn't initialized to 0

- src/execwrappers.cpp
- src/miscwrappers.cpp
- src/plugin/pid/pid_miscwrappers.cpp
This fixes DMTCP for aarch64 (ARM64).
It was failing for recent releases of Linux/libc for aarch64 primarily because the kernel for aarch64 had dropped its original aarch64 support for certain older kernel calls.  Presumably, this was because there were no (or almost no) aarch64 applications using those kernel calls since aarch64 is a newer architecture, and libc was now redirecting only to the newer kernel calls.  And, in principle, applications for Linux that were developed for other CPUs (as is the case for DMTCP) were assumed non-portable if they were making direct kernel calls.  So, we have now done that porting.
> Fixes for aarch64

- Makefile.in
Two lines are changed in the top-level `Makefile.in`.
This uses `python`, and in the case that python refers to Python3, the python print statement was failing because it was lacking the parentheses that are needed for Python3 syntax.
> Fix for DMTCP/Makefile.in for Python3

- src/threadlist.cpp
This paradigm is a standard trick to pause the process, and allow one to attach GDB and then do:  (gdb) p dummy=0  [and continue debugging.  But newer compilers can hide 'dummy' in a register, and GDB will then refuse to recognize that 'dummy' is an lvalue.  Making 'dummy' volatile instructs the compiler to retain 'dummy' as an lvalue for all optimizations.
> Add 'volatile' to:  int dummy=1; while(dummy){};

- test/syscall-tester.c
`tmpnam()` is deprecated in favor of `mkstemp()` for security reasons.  This PR updates `test/syscall-tester.c` to use `mkstemp()` instead of `tmpnam()`.
> syscall-tester.c:  tmpnam() -> mkstemp()

- src/mtcp/mtcp_restart.c
- src/mtcp/restore_libc.c
Commit 7d02a2e0 (PR #609) had enhanced x86_64 for per-thread fs reg., but it also broke the aarch64 version.  This fixes it.
> aarch64 fixes for src/mtcp directory

- src/rlimitfloatenv.cpp
- test/syscall-tester.c
The 'syscall-tester' was testing on RLIMIT_CORE, and we weren't restoring that.  So, `autotest.py --stress syscall-tester` was failing.
This PR includes about 7 additional RLIMIT_XXX values to save and restore.  It uses a macro to handle the repetitive code.
In addition, `test/syscall-tester.c` was modified to not test if crlim.rlim_max is restored.  There's no need for us to restore the maximum RLIMIT_CORE, since the new restart machine may allow a larger CORE limit.
> Saving and restoring more RLIMIT_XXX values

- Makefile.in
Currently, the display-build-env target of `Makefile.in` is executed in parallel with the `build` target.  As a result, the lst few lines of information in `make display-build-env` become intermixed with the first few lines of output from the 'g++' compilations.  This fixes that so that the 'display-build-env' happens first, followed by a blank line.
This also ensures that the build target 'dmtcp' happens only after 'mkdirs', although usually this doesn't cause a bug.  It's because the new directories are needed by the 'dmtcp' target only near the end of the build.
> Complete 'make display-build-env' before the rest of the build in 'make'

- test/autotest.py
* Force ptymode for zsh/tcsh.
* Disable plugins for vim. In complex setups, plugins could involve external processes such as ycm server for youcompleteme plugin.
> Autotest pty fixes for tcsh, zsh, and vim.

- configure
- configure.ac
This changes only `configure.ac` (and therefore `configure`).  When the user invokes:
```
/configure --enable-multilib
```
it now checks if the 32-bit libc and stdc++ libraries are available.  (Needed for mixed 32-/64-bit mode.)
This PR depends on PR #782 being merged first.
> ./configure --enable-multilib:  check if 32-bit libs available

- src/rlimitfloatenv.cpp
We shouldn't change rlimit on restore if the pre-ckpt limit was set to infinity.
> Rlimit: handle RLIM_INFINITY.

- src/coordinatorapi.cpp
- src/dmtcp_coordinator.cpp
I found a better fix for the original problem and for a second problem.  This new version has nothing to do with the earlier version under this PR.  The git commit also has some explanation.
(And the second commit is just to improve the error msg.  It was too small for a separate PR.)
[FROM git commit:]
- This fixes a long pause (e.g., GDB) when at main() in the target application. 
The ckpt interval timer goes off at this time 
- In addition, it fixes a problem of:  dmtcp_launch and break at execvp (e.g., in GDB) 
In this case also, the ckpt interval timer goes off, and the workerState is not yet running\
or the last worker exited and the worker state is UNKNOWN                                       
[FURTHER EXPLANATION:]
This fixes two bugs.  Both can occur when using GDB for debugging …
> Fix: Coord didn't reset alarm() if nothing running

- src/coordinatorapi.cpp
- Util::readAll() and Util::writeAll() return ssize_t, which is a
signed int when compiled in 32-bit mode.  When the result is
compared with a uint64_t, the gcc-4.8 compiler issues warnings
about comparing a signed and unsigned int expression.  So, we
cast the other comparison expression to an 'ssize_t'.
> Compiler warnings w/ -m32 for coordinatorapi.cpp

- src/dmtcp_dlsym.cpp
Other plugins might call dmtcp_dlsym without holding ckpt-lock and can introduce a deadlock if the ckpt-thread suspends a user-thread while it is holding an internal dlsym lock. Later on, ckpt-thread will deadlock if it also tries to call dmtcp_dlsym.
> Disable ckpt while processing dmtcp_dlsym.

- src/coordinatorapi.cpp
- src/dmtcp_command.cpp
- src/dmtcp_coordinator.cpp
- test/autotest.py
Logically, the dmtcp_coordinator is asking to "kill the peers after checkpoint".  'xc' ('--exit-after-ckpt' flag) was getting confused with the dmtcp_coordinator flag:  '--exit-on-last'.  So, now we have:
`--kill-after-ckpt` and `--exit-on-last`.  So, we also change 'xc' to 'kc' to correspond.
I've tested this locally, and it works for me.  This is ready for review.
====
As for the history, the 'xc' command was never documented to users.
In the usage command for src/dmtcp_command.cpp, the 'xc' command was commented out in 2013 at commit ee798b0 .   (Maybe it was always commented out.)  The commit comment says "
```
The command to set the flag is 'x' and it must be followed by a 'c'
command.
Not documenting it right now to allow a name/letter change later.
```
I guess it's about time to …
> dmtcp_coordinator: Change 'xc' (ckpt & exit) to 'kc' (ckpt & kill peers)

- src/miscwrappers.cpp
- src/wrappers.cpp
If dup2() or dup3() tries to copy an fd into a protected fd, then we detect that, and JASSERT.
> dup2/dup3 now check if they're copying to prot. fd

- include/dmtcp.h
The change in `include/dmtcp.h` is a comment that says it all.
> Add comment for include/dmtcp.h: dmtcp_checkpoint() -- this is blocking on current thread

- src/processinfo.cpp
- src/procselfmaps.cpp
- src/writeckpt.cpp
This pull request adds a guard page at each end of the restore-buffer memory region to make sure that the region is not merged with the same permission pages in proc maps. DMTCP can then correctly identifies and skip this region to write into a checkpoint image. (see mtcp_writememoryareas function in src/writeckpt.cpp)
> Add guard pages to restore-buffer memory region

- src/mtcp/mtcp_header.h
- src/mtcp/mtcp_restart.c
- src/processinfo.cpp
- src/processinfo.h
- src/threadlist.cpp
The stack region of user-application doesn't grow automatically on the restart in the absence of MAP_GROWSDOWN mmap flag while remapping user-applications' memory regions. The current version of DMTCP gives segmentation fault if the user application tries to extend the stack downwards by touching any address within guard page region.
> Fixed code to add MAP_GROWSDOWN flag for stack region

- src/mtcp/mtcp_restart.c
- src/threadlist.cpp
- util/gdb-add-libdmtcp-symbol-file.py
- util/gdb-add-symbol-files-all
Extended to include more variations of 'add-symbol-file-XXX'; some bug fixes added,
including a bug fix for `(gdb) add-symbols-files-all`
1. read the beginning of util/gdb-add-symbol-files-all for the GDB commands added
2. Comment at beginning of util/gdb-add-libdmtcp-symbol-file.py makes clear that it
is deprecated in favor of util/gdb-add-symbol-files-all
Typical usage:
```
(gdb) source util/gdb-add-symbol-files-all
(gdb) add-symbol-files-all
```
> util/gdb-add-symbol-files-all: extended & polished

- src/mtcp/mtcp_restart.c
- src/mtcp/mtcp_util.h
- src/mtcp/mtcp_util.ic
1.  Add `mtcp_strrchr()` to mtcp_util.ic  (mtcp_strchr()) is already there.
2. Fix bug in `mtcp_util.ic:mtcp_strcpy()`.  (It wasn't copying the final '\0'.)
3. Fix minor bug:  `/proc/*/mappings` was inside a comment.  The Intel icc compiler was catching this as `*/' (end-of-comment).  (It was inside a '#if 0 ... endif', and so the compiler only generated a warning.)
> Define mtcp_strrchr; Fix mtcp_strcpy: final '\0'

- configure
- configure.ac
* If mpicc not present, ./configure lead to extraneous printouts
> configure.ac: Check mpicc better at --with-mpich

- src/processinfo.cpp
- src/writeckpt.cpp
Add PROT_READ to guard page of restore buffer
* This works around a Linux 3.10 kernel bug affecting sched_test. 
* A second commit also does a JASSERT if writeAll() in ckpt of a memory segment fails.
Note that PROT_READ was added to 'mprotect' on the guard pages around the restore buffer.  Without this, writeAll was failing on the guard pages during ckpt in the child process, in the case of test/{dmtcp5,sched_test,shared-fd1} and other tests during the _first_ checkpoint, only.  write() was failing with EFAULT (but no SEGFAULT) for the guard pages in Linux 3.10.0-1062.9.1.el7.x86_64 in CentOS 7.7.1908.  (But it did not occur in Ubuntu 18.04 with Linux 4.15.)  This is arguably a bug in the Linux 3.10 kernel.
> Add PROT_READ guard pages

- test/epoll1.c
The title says it all.  getsockname() was not being used correctly.  More recent glibc's do better testing.
> Fix for test/epoll1.c:  Fixing commit b02d3e867d1

- include/util.h
- src/dmtcp_launch.cpp
- src/execwrappers.cpp
- src/util_exec.cpp
> Fix exec of shell script

- .travis.yml
- util/dmtcp_backtrace.py
.travis.yml modified to add scirpt_failure: entry to cat /tmp/dmtcp-*/backtrace.* files.
> github/travis: cat /tmp/dmtcp-*/backtrace.* debugging files on jassert

- Makefile.in
- configure
- configure.ac
- util/dmtcp-style.py
- util/hooks/post-rewrite
- util/hooks/pre-commit
The top-level `Makefile.in` and `.git/hooks/{pre-commit,post-rewrrite}` were modified so that they will invoke python or python3 -- whatever is available.
* This now also works when 'python3' is available, but not 'python'.
> Makefile.in, hooks/{pre-commit,post-rewrite}: use Python 2 or 3

- test/autotest.py
The POSIX version of 'ps' says that 'args' is a format option, but not 'command'.  We change this to make autotest.py more POSIX compliant.  This should be easy to review.
> autotest.py: 'ps -o command' -> POSIX 'ps -o args'

- test/autotest.py
- test/plugin/presuspend/presuspend.c
Fix to a silly bug:  pthread_kill was used instead of kill() for a childpid.
This should be trivial to review.
> Fix for test/plugin/presuspend.c: bad use of pthread_kill()

- test/autotest.py
autotest.py was sometimes failing on 'login' computer during the emacs test, at the first restart.  This sets POST_LAUNCH_SLEEP to a longer 3 seconds.
> Fix autotest.py for slow emacs restart

- src/mtcp/mtcp_restart.c
This is a trivial PR to review.  I'm removing one comma  (and changing a print string).
* Remove misplaced comma in DMTCP_RESTART_PAUSE msg in mtcp_restart.c
* Improve msg about issue with Linux/glibc/gdb
> Minor bug fix for a0567cbd (and improved text): DMTCP_RESTART_PAUSE msg changed

- src/mtcp/mtcp_restart.c
In mtcp_restart.c function read_one_memory_areas(): limit using string comparison to identify a stack region to regions whose name is not filename starting with "/".
This fixes a problem with dmtcp_restart failing to mmap a file whose path name includes the substring "stack" because  the MAP_GROWSDOWN flag gets used.
> Bug fix for misidentifying region as stack

- fedora/dmtcp.spec
@pgrosu and I are in the last stages of getting the DMTCP-2.6.1 package accepted into Fedora.  Soo, this commit updates the fedora/dmtcp.spec for the master branch, based on the mentoring we received for including dmtcp.spec in DMTCP--2.6.1.  This should be easy to review: this dmtcp.spec was accepted by Fedora for the 2.6.1 version of DMTCP.
> Update fedora/dmtcp.spec w/ info for 3.0 release

- fedora/dmtcp.spec
fedora/dmtcp.spec:  `Release:        0.0%{?dist}`  (Previous commit was `0.1%(?dist)`.)
> Fix for 9add8d: fedora/dmtcp.spec for DMTCP 3.0

- test/autotest.py
This fixes a long-standing bug that affected `./autotest.py --slow syscall-tester`.  The autotest file uses `b'Kc'` to do an exit after checkpoint that kills the process after the first checkpoint.  As explained in the autotest.py file, this is needed for a correct test in case of syscall-tester calling 'unlink'.  But autotest.py had a line that expected the process to resume after checkpoint.  If `b'Kc'` is used, the process will _not_ resume after checkpoint.  So now, if `b'Kc'` was used, it's not an error if the process doesn't resume.
> autotest.py syscall-tester: ckpt w/ -Kc: no resume

- src/coordinatorapi.cpp
- src/dmtcp_command.cpp
- src/dmtcp_coordinator.cpp
Two commits:
1.  `dmtcp_command -l`     now works.  This bug has been in DMTCP forever.
2.  `top` and `ps` should now show the port number for dmtcp_coordinator.
> Fix 'dmtcp_command -l' and show port w/ 'ps', 'top'

- src/ckptserializer.cpp
- src/ckptserializer.h
- src/dmtcpworker.cpp
- src/processinfo.h
- src/threadlist.cpp
This helps prevent partial checkpoints when a large process takes long time to write a ckpt image.
> Delay *.ckpt.temp to *.ckpt rename until after WriteCkpt barrier.

- util/gdb-dmtcp-utils
Some more enhancements to `util/gdb-dmtcp-utils`.  For example
```
whereis-address $pc
```
now works.  Also, the comments in `util/gdb-dmtcp-utils` referred to its old filename (`util/gdb-add-symbol-files-all`).  This fixes it.
> util/gdb-dmtcp-utils: Further enhancements

- include/shareddata.h
- src/dmtcp_coordinator.cpp
- src/dmtcp_restart.cpp
- src/dmtcpworker.cpp
- src/plugin/ipc/file/fileconnlist.cpp
- src/shareddata.cpp
We removed the numPeers check when we moved to the newer barrier design. This PR reintroduces the concept.
> Ensure all restarting processes have connected before releasing a barrier.

- plugin/pathvirt/pathvirt.cpp
- src/plugin/ipc/file/ptywrappers.h
- src/plugin/pid/pid_syscallsreal.c
- src/plugin/pid/pidwrappers.h
- src/syscallsreal.c
- src/syscallwrappers.h
DMTCP fails to compile with glibc-2.33.  In particular, the future release of  Fedora 2.34 (and other distros) will start to use gcc-10.0 and glibc-2.33.
The problem is that in glibc version 2.33, they stop defining `_STAT_VER`.  glibc originally used `_STAT_VER` as the value in an extra argument in `__xstat(vers, path, buf)` .  Presumably, gcc/g++ then macro-expanded `stat(path,buf)` to `__xstat(_STAT_VER,path,buf)`.  But glibc-2.33 now removes `_STAT_VER` and directly defines `stat(path,buf)`, etc.
This PR uses `#ifdef _STAT_VER` to have DMTCP refer either to `__xstat()` or `stat()`, according to whether `_STAT_VER` is defined.
**NOTE:**  mknod() in test/syscall_tester.c also uses _STAT_VER prior to glibc-2.33.  In Fedora rawhide, test/syscall_tester.c fails even without using DMTCP, …
> Fix for master branch for glibc 2.33 using stat() family

- .travis.yml
- src/restartscript.cpp
When libgen.h is included, then glibc uses POSIX `basename()` instead of GNU `basename()`.  The GNU version takes a `const char *` argument.  But the POSIX version takes a `char *` as its argument, since it may choose to destructively alter its string argument.  So, we make a `char *`  local copy of the string to pass to GNU `basename()`.
> Stop using cast for basename (Fix for 97d45952)

- src/dmtcp_coordinator.cpp
- test/autotest.py
`dmtcp_coordinator.cpp` now takes a `--timeout <seconds>` flag.  If the timeout occurs, then the coordinator exits.
This is useful in `autotest.py`.  This was now changed to call `./bin/dmtcp_coordinator --timeout 10800` (a timeout of 3 hours).  This should get rid of the frequent runaway coordinator processes that occur when `make check` is interrupted.
> Add --timeout param to coord; use it in autotest

- test/autotest.py
The `file2` test creates several megabytes in `/tmp`.  The test fails when there is not enough disk space in `/tmp`.  However, `autotest.py` simply shows that `file2` is failing, with no clues that the problem is disk space.  This can be a problem when many debugging sessions cause large DMTCP-related files and directories to accumulate in `/tmp`.
This PR now tests for this condition, and prints out a warning just before the tests execute.
> autotest.py: Check for low disk space in /tmp

- test/autotest.py
In the script test and the shell tests (python, perl, bash, dash, tcsh, zsh), `POST_LAUNCH_SLEEP` is set to 2 seconds before the test.  This is needed because the shells need to launch complex commands with one or more child processes.  We need to wait until they are launched before checkpointing, or else the test fails because too few processes were checkpointed.
> autotest.py:  Fix params for script, bash, etc.

- jalib/jalloc.cpp
- plugin/batch-queue/rm_main.cpp
- plugin/modify-env/modify-env.c
- src/dmtcp_coordinator.cpp
- src/dmtcp_get_libc_offset.c
- src/dmtcpplugin.cpp
- src/plugin/pid/pid.cpp
- src/util_exec.cpp
This fixes various compiler warnings from gcc/g++ version 10.0.
> 3.0-fix-gcc-10-warnings

- src/mtcp/mtcp_restart.c
This pull request fixes a bug occurring in `mtcp_restart.c` when a vdso or vvar segment doesn't exist, which may result in undefined behaviour in some functions since they were written with the assumption that these segments are non-zero in size.
> Fix a bug when vvar/vdso segment does not exist

- src/dmtcp_coordinator.cpp
The coordinator incorrectly decrements the workersAtBarrier counter
when a process disconnect from the coordinator.
> Fix coord. hangs if a process exit before barrier

- src/plugin/pid/pidwrappers.cpp
- test/Makefile.in
- test/autotest.py
- test/gettid.c
This is a first attempt at creating a DMTCP wrapper for gettid().  It also creates a test:  `test/gettid.c`
Note that gettid() was defined in GLIBC starting with GLIBC-2.30.
> WIP: If GLIBC-2.30: support gettid(), add test/gettid.c

- src/coordinatorapi.cpp
- src/dmtcpplugin.cpp
- src/execwrappers.cpp
- src/miscwrappers.cpp
- src/syslogwrappers.cpp
Statically allocated string required at_exit/on_exit handlers to be
registered with libc. This can cause weird deadlocks because the
on_exit/at_exit handle registration requires manipulating libc-internal
linked lists with low-level libc locks and malloc/calloc/free calls.
If the static string is not getting initialized during checkpoint phase, a
deadlock is less likely. But during a checkpoint, the probability rises
significantly.
Added a wrapper for on_exit to ensure we don't checkpoint in the middle
of exit handler registration.
> Removed statically allocated strings.

- src/Makefile.am
- src/Makefile.in
- src/coordinatorapi.cpp
- src/dmtcp_coordinator.cpp
- src/dmtcp_coordinator.h
- src/dmtcp_dlsym.cpp
- src/dmtcpworker.cpp
- src/execwrappers.cpp
- src/threadsync.cpp
- src/threadsync.h
- test/autotest.py
- test/vfork1.c
Since user threads are not quiesced until after processing
DMTCP_PRESUSPEND event, a user thread might exec after receiving
DMT_DO_CHECKPOINT msg from the coordinator. After exec completes, the
process will wait for a new DMT_DO_CHECKPOINT msg while the coordinator
is waiting for all workers to reach the DMT:SUSPEND barrier.
The fix is to send a duplicate DMT_DO_CHECKPOINT message if a checkpoint
is in progress when a worker reconnects to the coordinator after exec.
We also handle the possibility of doing an exec even before receiving
DMT_DO_CHECKPOINT message. In that case, the worker will receive two
DMT_DO_CHECKPOINT messages and will safely ignore the second one.
> Handle workers that exec after PRESUSPEND.

- src/plugin/pid/pidwrappers.cpp
This fixes PR #931 .  I had an extraneous '!' character.  :-(
> Support glibc:gettid(); fix for commit ae40d86

- plugin/modify-env/modify-env.c
- src/dmtcp_coordinator.cpp
gcc-9.3 issued a warning about signed and unsigned for:
`(time(NULL) - start_time) >= (timeout - 1))`
clang++-3.4 issues a warning for dmtcp_cooordinator.cpp.
So, `sttrncpy()` and `#pragma` are being replaced by `memcpy()`
STYLE:
`#include "dmtcp_coordinator.h"` moved after system includes
> Comp. warn's: dmtcp_coordinator.cpp, modify-env.c

- util/gdb-dmtcp-utils
1. Improved 'help' message when it's first loaded
2. whereis-address also works with data segments and segments with no permission now.
3. It also now displays the permissions of the segment that it finds.
> Enhance and fix gdb-dmtcp-utils (data seg, perm)

- configure
- configure.ac
- test/Makefile.in
- test/syscall-tester.c
The revision to the BasicMknod test of `syscall-tester.c` is failing on Suse Enterprise 15 (Linux 4.12, gcc-7.5, glibc-2.26).
This PR reverts the changes to BasicMknod that were made in PR #937, while keeping the other improvements.
```
--- Line 4154: BasicMknod() ---
mknod(): path=/tmp/dmtcp-syscall-tester-FzrRG8, mode=0x21c0(020700), dev=0
ret = -1      
Succeeded Phase 1
BasicMknod():4161
Failed Phase 2: This call did something unexpected.
BasicMknod():4161
Fail Phase 2: Aborting test because of catastrophic failure
Ending Test: [BasicMknod: Can I make pipes and not other stuff?]
------------------------------------------------------------- 
```
As a side comment, the previous PR #937 causes BasicMknod to always fail on Suse Enterprise 15.  On CentOS 7, _with this PR that reverts it_, …
> syscall-tester.c: revert BasicMknod test changes

- util/gdb-dmtcp-utils
This extension supports `(gdb) procmaps`, etc., when GDB is sued to debug a core file.  It relies on `(gdb) info proc mapping` here, in addition to the usual `(gdb) shell cat /proc/PID/maps`.
> Extend util/gdb-dmtcp-utils to work w/ core files

- src/mtcp/mtcp_restart.c
- src/plugin/ipc/connection.cpp
* As of Windows 21H!, WSL is now mature.  We don't need the special cases.
> Remove '#ifdef WSL' and WSL comments

- src/mtcp/sysdep/sysdep-x86_64.h
The original code `(unsigned long)(val) >= -4095L) ` produces a warning on recent gcc compilers.  And `(long)(val) >= -4095L) ` (used in commit 073e69a) is fine on recent compilers, but it compiles to incorrect semantics in gcc-4.8  So, this commit now changes it to:  `(unsigned long)(val) >= -4095L) `, which seems to satisfy both versions of gcc compilers.
> Fix for commit 073e69a, to support gcc-4.8

- include/dmtcp.h
- jalib/jalloc.cpp
- src/dmtcpworker.cpp
- src/threadlist.cpp
- test/plugin/presuspend/presuspend.c
- test/shared-memory1.c
* ISO C does not guarantee that an int is aligned.  So, it won't be
atomic if it crosses a cache boundary.  This adds ATOMIC_SHARED macro.
@gourryinverse convinced me that the ISO C standard says that C doesn't have to respect a 4-byte int (e.g., on x86_64) as atomic, and that it can still be misaligned.  ISO C says that a struct must respect the chosen alignments of its fields, but it doesn't seem to say what is the "natural" alignment of an int.
As an interesting example, consider this partial evidence provided by him.  An 8-byte pointer turns out to be only 2-byte aligned.  So, maybe the compiler normally aligns 4-byte int's correctly, but we can't depend on that.  This is all about evidence, since we have no way of directly proving what a compiler is required to do.
```
#include …
```
> volatile -> volatile __attribute((aligned))

- jalib/jalloc.cpp
The __attribute((aligned)) causes the struct to grow beyond double-word,
causing CAS to fail. Since this field is updated safely, we don't need it to be
volatile.
> Removed volatile from StackHead definition.

- test/Makefile.in
- test/autotest.py
- test/clone1.c
@karya0,
This `test/clone.c` segfaults on `bin/dmtcp_launch test/clone1`.  This has been the case since PR #932 .  Admittedly, prior to PR #932, we could launch, checkpoint, and resume clone1, but we were failing to restart clone1.
Nevertheless, even if we comment out 'clone' in `atuotest.py`, this seems like a good test to have in reserve for the future.
If we need to, we can simply check it in, with this test commented out.
But I'm hoping that this will help you to analyze your PR #932.  Maybe there's something simple there that you can easily fix.  To test, just do:
&nbsp;&nbsp;&nbsp;&nbsp; `make -j check-clone1 && bin/dmtcp_launch test/clone1`
> Adding clone1 test (emulating child thread)

- include/procmapsarea.h
- src/mtcp/mtcp_restart.c
- src/procselfmaps.cpp
- src/writeckpt.cpp
The issue is related to the fact that an application is allowed to
mmap a large region of memory even though the entire region may not be
backed by a file. For example, for a file that is just 1 MB on disk,
the application can make an mmap call asking for 2 GB, but only the
first 1 MB of the memory region will be actually made available. There
are two different behaviors of the Linux kernel when one tries to read
anything beyond the first 1 MB:
- If one tries to read any byte in user-land (load instruction) beyond the first
1 MB, it generates a SIGBUS.
- If one makes a system call such as write() that uses the entire memory
region (2 GB), the system call returns success, meaning that it wrote
2 GB, but it actually only writes out 1 MB!
Now, this confuses the restart code: since we …
> Fix checkpoint-restore of file-backed regions

- src/wrappers.cpp
Previously, the return value is the same as the input. Also in many places, the return value of the realToVirtualPath is not used. 
For this family of functions, it passes in a pointer to char as a buffer. But there is no buflen. This design seems fragile. Sometimes a function overwrites the buffer without checking the buflen. The current code seems to depend on PATH_MAX, but it has no way to verify the path length.
@karya0, could you improve on this PR?
> Fixed a bug in realToVirtualPath

- doc/debugging-dmtcp.txt
- include/dmtcp.h
- jalib/jassert.cpp
- src/dmtcp_launch.cpp
* JASSERT had recognized DMTCP_ABORT_ON_FAILED_ASSERT
* Change behavior to abort on all failures, change var. name
Previously, there was no easy way to ask DMTCP to abort on exit with failure.  This generalization helps us to debug DMTCP internal errors, and perhaps it's useful also when an end user hands DMTCP some improperly structured data, causing DMTCP to abort.
This PR should be easy to review.  It was motivated by a previous effort with @xuyao0127 to debug a DMTCP internal error.
> Check for env var DMTCP_ABORT_ON_FAILURE

- util/gdb-dmtcp-utils
This fixes a bug where it was improved in one direction, but stopped working on core files (using `(gdb) info proc mapping`).  This has also been tested by @xuyao0127 for core dumps for debugging MANA.  It worked there.
The PR is also being added to MANA:master .
> Fix e37c9b9ba for 'core' for gdb-dmtcp-utils

- src/mtcp/Makefile.in
- src/mtcp/mtcp_restart.c
Newer Linux kernels may place vdso and vvar in rather arbitrary locations.  On restart, we must mremap the vdso/vvar of the current mtcp_restart.c to the vdso/vvar address from the original pre-checkpoint process.  But if the current vdso/vvar overlaps with the mremap destination, then the mremap fails.
This commit mremap's to a temporary mmap'ed memory region that doesn't overlap, and then it mremap's again to the final destination.
* In addition, there is a second commit that changes `-Wl,-Ttext-segment=11100000` to `-Wl,-Ttext-segment=11200000`.  The address must be a multiple of the pagesize, and a 2M hugepage is `0x200000`.  So, this is needed to be compatible with hugepages.
> Fix: src and dest of mremap_move may overlap in mtcp_restart.c

- src/dmtcp_coordinator.cpp
In commit ad90917, the Resume_resume barrier is removed. Therefore, the minimum state when the checkpoint is complete is no longer WorkerState:RUNNING, it's WorkerState:CHECKPOINTED. So releaseBarrier will never reset the checkpoint timer.
> Fix for commit ad90917: unable to reset ckpt timer

- src/Makefile.am
- src/Makefile.in
- src/dlwrappers.cpp
- src/plugin/svipc/sysvipcwrappers.cpp
I'm open to suggestions for possible improvemets:
1.  We probably want to move this code to somewhere in `libdmtcp.so`, but to which file?
2. This code improves on the previous `dlsym()` wrapper.  That code assumed that `RTLD_NEXT` is used only to wrap a function in libc.so.  However, it's not perfect.  Is there a __simple__ way to improve on this?  (If it's not simple, then this is good enough for now.  "The perfect is the enemy of the good.")
For convenience, I'm copying here the comments found in `src/plugin/svipd/sysvipcwrappers.cpp`:
```
//   We need to wrap dlsym to disable and re-enable ckpt.  But then,
// dlsym(RTLD_NEXT, ...) no longer works, since glibc:dlsym() looks up
// the stack to find the caller's library, and discovers a DMTCP library
// instead of the original target …
```
> Fixes call by target of dlsym(RTLD_NEXT,...)

- util/gdb-dmtcp-utils
- Doesn't work with coredump file with getpid() == 1
- Minor fix from MANA 0f8b15eb8
> Cherry-pick 2 fixes for `gdb-dmtcp-utils`

- include/dmtcp.h
- src/jalibinterface.cpp
The definition of DMTCP_FAIL_RC is changed in [this](https://github.com/dmtcp/dmtcp/commit/14932be2ab71fc0bc5b700b618c3f12e0d128b62) commit. If getenv(DMTCP_ABORT_ON_FAILURE) returns 1, DMTCP_FAIL_RC will call abort() immediately. However, DMTCP_FAIL_RC is used as the last parameter of the function jalib_init. Therefore, before calling jalib_init, DMTCP_FAIL_RC is expanded and evaluated in order to get the value of the parameter. Then because the environment variable DMTCP_ABORT_ON_FAILURE is defined as 1, the program will call abort() immediately.
> Bugfix - abort() is being called before jalib_init() because of DMTCP_FAIL_RC macro evaluation.

- src/plugin/ipc/file/fileconnection.cpp
This change cherry-pick the warning for checkpoint file size change from commit a1583a "Deterministic p2p".
> Cherry-pick dmtcp change from commit a1583a "Deterministic p2p".

- src/plugin/svipc/sysvipc.cpp
- src/plugin/svipc/sysvipc.h
Replaces a dynamically allocated array with a vector.
The delete operation in destructor should have been JALIB_FREE instead.
We don't need to use a dynamic array anyway, since a vector works just as well.
> Fixed Sys V Semaphore bug related to delete.

- src/dmtcp_launch.cpp
- src/mtcp/Makefile.in
- src/plugin/ipc/file/fileconnlist.cpp
@karya0 @gc00 There are three commits in the feature/mana branch now. We need to take a look at some of these commits before we can take them to the DMTCP.
1. 1df553b97f60608d46b40839b4fd793ed2ddc3b4: This commit added more keywords in the `FileConnList::prepareShmList()` function to skip some MANA related regions. I remember Kapil said he will work on a way that plugins can add more keywords without modifying DMTCP.
2. 08e4c8d2469f9bbe986744d94bafd2071c39847a: This commit revert a previous commit 764a55f917c7a4abaa0183cada8b9f1934bfab99 that added a compile option that is no longer needed.
3. 4bd4fa6dc3dbe9ceaa7ad9669d3fab7eaecb99dc: This commit is part of a commit in MANA's master branch that renames `libmpidummy.so` to `libmpistub.so`. `dmtcp_launch.cpp` is also modified because if …
> Changes from feature/mana

- src/mtcp/Makefile.in
Without -static, gcc generates a dynamically linked mtcp_restart on
Ubuntu 22.04.
Addresses #990.
> Use -static when compiling mtcp_restart.

- include/dmtcp.h
- include/dmtcpalloc.h
- src/dmtcp_restart.cpp
- src/dmtcpplugin.cpp
- src/dmtcpworker.cpp
- src/execwrappers.cpp
- src/miscwrappers.cpp
- src/rwlock.cpp
- src/threadinfo.h
- src/threadlist.cpp
- src/threadlist.h
- src/threadsync.cpp
- src/threadsync.h
- src/threadwrappers.cpp
- src/tls.cpp
- test/autotest.py
- test/clone1.c
Simplified wrapper-lock mechanism to use per-thread state to keep count of read-locks.
Further, this PR also removes support for raw clone calls. We currently can't support raw thread-creation calls to clone and clone3 due to TLS. DMTCP relies heavily on TLS for maintaining user-thread state. It includes the thread-local curThread struct as well as some other locks and variables maintained by pid plugin, etc.
Threads created using clone3/clone either shouldn't use TLS or should lay out TLS exactly the way libpthread expects. A thread without a properly laid out TLS segment would fail on calling any libc or libdmtcp functions that deal with TLS. Since a user-thread needs to call several functions within libdmtcp, a lack of TLS will result in random/hard-to-chase failures.
Since there are …
> Better wrapper-lock mechanism

- src/dmtcp_coordinator.cpp
- src/dmtcp_launch.cpp
- src/dmtcp_restart.cpp
Option "--help" and "--version" are valid options for dmtcp_launch, dmtcp_restart and dmtcp_coordinator. The command should return value should be "0" when the valid option is present.
> Return success for the valid options

- include/shareddata.h
- src/dmtcp_restart.cpp
- src/dmtcp_restart.h
- src/dmtcpplugin.cpp
- src/dmtcpworker.cpp
- src/processinfo.cpp
- src/processinfo.h
- src/shareddata.cpp
Initializing static members relied on untimely usage of new, causing deadlock due to malloc wrappers, etc..
> Moved static members from dmtcpplugin to ProcessInfo.

- src/threadlist.cpp
- src/tls.cpp
Dynamic offset calculation fails sometimes due to a false hit (when tid
matches some bytes in the tcbhead struct).
Fixes #994.
> Always use static TLS TID offset.

- include/shareddata.h
- include/util.h
- jalib/jalib.cpp
- jalib/jalib.h
- jalib/jassert.cpp
- jalib/jassert.h
- jalib/jconvert.h
- src/Makefile.am
- src/Makefile.in
- src/dmtcp_coordinator.cpp
- src/dmtcp_launch.cpp
- src/dmtcp_restart.cpp
- src/dmtcpworker.cpp
- src/execwrappers.cpp
- src/jalibinterface.cpp
- src/plugin/ipc/event/eventwrappers.cpp
- src/processinfo.cpp
- src/shareddata.cpp
- src/signalwrappers.cpp
- src/util_init.cpp
Here are some of the improvements:
* File names:
* One file per process (an exec will not create a new file)
* Separate files for dmtcp_* commands.
* Worker files named $TMP/dmtcpworker.<Timestamp>.<UniquePid>.log.
* Logs messages:
* Add timestamp along with pid, tid and type (error, warning, etc.).
* Always add a backtrace on JAssert failure;
* Add /proc/self/maps contents to log on Jassert failure
Other code cleanup.
> Various logging improvements.

- util/fsgsbase-enabled.c
This is a useful quick test with the MANA plugin, to see if the user-space FSGSBASE patch is present, when calling the lower half.
> Util to test for FSGSBASE patch; info on use

- configure
- configure.ac
Local,  minor changes to configure.ac:
1. OUTPUT: `checking whether GNU_HASH is supported for ELF... (DT_GNU_HASH: 1879047925) yes`
(Added '(' and ')' around `DT_GNU_HASH` for clarity.
2. configure.ac:  `#define _GNU_SOURCE ` -- remove extra space at end of line
3. configure.ac:  remove:  `AC_MSG_RESULT([$epoll_create1])`
(This causes an extra blank line to appear after `checking if epoll_create1 available... checking for epoll_create1... yes`;
when the previous `AC_MSG_CHECKING([if epoll_create1 available])` already emitted `yes`.)
> Polish configure.ac/configure

- src/mtcp/mtcp_restart.c
- src/mtcp/mtcp_util.c
- src/procselfmaps.cpp
- src/writeckpt.cpp
- test/autotest.py
- test/shared-memory3.c
Previously, checkpoint-restart was not properly preserving zero pages in the case of SysV shared memory (SYSV000XXX memory segments), when hugepages were enabled.  As a result, on restart, the memory being used by the process would grow because those zero pages would be replaced by actual pages of zeroes.
This is code from @karya0 and based on his branch.  He asked me to create the PR.  This should fix a case where MANA was using excessive RAM  on restart.
> Shm hugetlb

- jalib/jassert.cpp
- src/util_init.cpp
std::put_time was introduced in commit b2823e39 (July, 2022)
Apparently, gcc-4.8 (and therefore CentOS 7) doesn't support it.  I added a conditional around it: `#if __GCC__ > 4`
> For gcc-4.8, std::put_time was failing

- configure
- configure.ac
- include/config.h.in
This is for a cross-configure.  DMTCP tests the local machine for the FSGSBASE kernel patch.  But the FSGSBASE kernel patch might be installed on the build computer, but not on the login computer. This flag will define a macro, HAS_FSGSBASE_OVERRIDE, and any package using DMTCP as a submodule can inherit this macro with a '#include "config.h"'.
> Add flag, --enable-fsgsbase-override

- include/procmapsarea.h
- src/constants.h
- src/mtcp/mtcp_restart.c
- src/writeckpt.cpp
Instead of mmapping zero-page segments in chunks, we now save a "parent" header in the ckpt-image followed by several "child" headers. The parent header is used only for making the appropriate mmap call. The data-restoration relies on child headers. Each child header is either marked as zero-page segment, in which case, there is no further action needed. For non-zero child segments, the restoration reads the saved data from ckpt image.
> Updated zero-page restoration support.

- include/util.h
- jalib/jalib.cpp
- jalib/jalib.h
- jalib/jassert.cpp
- src/jalibinterface.cpp
- src/util_init.cpp
- src/util_misc.cpp
It resolves the issue related to missing std::put_time on older compilers.
> Replaced std::puttime with Util::getTimestampStr().

- src/mtcp/mtcp_util.c
Perlmutter supports MAP_FIXED_NOREPLACE flag. Use this flag to guarantee the memory reservation is at the specified place.
> Use MAP_FIXED_NOREPLACE flag

- src/mtcp/mtcp_util.c
Cherry-pick this fix to master branch.
Use MAP_FIXED_NOREPLACE flag
Perlmutter supports MAP_FIXED_NOREPLACE flag. Use this flag to garantee the memory reservation is at the specified place.
> [Cherry-pick] Use MAP_FIXED_NOREPLACE flag (#1058)

- src/dmtcp_launch.cpp
* When the '--mpi' flag is set, do 'personality(ADDR_NO_RANDOMIZE)'.
* When restarting an MPI application, it is easier if the libraries, stack, vdso, etc., were loaded all at the same address for each MPI process/rank, prior to the checkpoint.
> dmtcp_launch: Add --mpi flag: personality(ADDR_NO_RANDOMIZE)

- src/dmtcp_dlsym.cpp
- test/autotest.py
- test/dlopen1.c
- test/dlopen2.cpp
`man dlopen` says 
> If filename contains a slash ("/"), then it is interpreted as a  (relative or absolute) pathname.  Otherwise,  ...
So, `dlopen("libdlopenX.so")` is changed to  `dlopen("test/libdlopenX.so")`.  The test always runs from `../test`.  We were previously using `LD_LIBRARY_PATH` in autotest.py, but doing this instead is simpler and more direct.
This seems good enough for Centos 7 (glibc-2.17) to work on dlopen1 and dlopen2 both.
The CI then uses Ubuntu 22.04.  On dlopen1, it launches, but does not checkpoint.  (Previously, it did not launch.)
In WSL/Ubuntu 22.04, I was able to reproduce the bug.  The commit `Fix dlsym_default_internal_library_handler()` then sufficed to fix the bug that was exposed for Ubuntu 22.04.
> FIx dlopen tests: dlopen("libdlopenX.so") -> dlopen("test/libdlopenX.so")

- util/readdmtcp.sh
Some sites might have an old system-wide copy of mtcp_restart in `/usr/bin/mtcp_restart`.
When invoking `DMTCP_ROOT/util/readdmtcp.sh`, the script now checks for a relative binary in `DMTCP_ROOT/util/../bin/mtcp_restart`, instead of blindly trying `which mtcp_restart` first.
> readdmtcp.sh: Prefer mtcp_restart of same dir tree

- configure.ac
- doc/README
- doc/debugging-dmtcp.txt
- include/dmtcp.h
- src/dmtcp_restart.cpp
- src/mtcp/mtcp_restart.c
- src/mtcp/mtcp_restart.h
- src/pluginmanager.cpp
- src/threadlist.cpp
When using DMTCP_RESTART_EVENT, it's useful to stop in an application's plugin at the time of restart.  Level 6 is before the restart event is handled and 7 is after the restart event is handled.
* This pauses at beginning of restart event before all plugins (5), or the end of restart event after all plugins (6).
The previous PAUSE=5 is now PAUSE=7, since it occurs after PAUSE=5,6. 
* This also fixes a bug in commit 7bc9fddf0 (two DMTCP_RESTART_PAUSE's at level 1: inside mtcp_restart.c and inside threadlist.cpp).
Finally, this PR has been updated to stop at a macro, `DMTCP_RESTART_PAUSE_WHILE(restartPauseLevel==3)`, rather than `DMTCP_RESTART_PAUSE(3)`.  The user can then modify `restartPauseLevel` and even change it to the next larger integer.  This is clearer than using hidden variables …
> Add DMTCP_RESTART_PAUSE={6,7}: to stop at a plugin using the DMTCP_RESTART_EVENT

- test/autotest.py
- test/dlopen1.c
- test/dlopen2.cpp
`dlopen[12].c` now does chdir to DMTCP root in beginning.  This makes it work even when doing something like:
```
/usr/local/bin dmtcp_launch ./test/dlopen1
```
since the required `./test/libdlopen[12].so` is in the same directory as `./test/dlopen1`.   It should also work with `./dlopen1` providing the current directory is in a directory, `test`, which contains `dlopen1`.
* Also, some very minor polishing of `autotext.py` is included here.
> Minor: dlopen[12] now works from any dmtcp_launch

- src/writeckpt.cpp
`JTRACE("...")(a.addr);` is being called on `a.addr`, which is a `char *`.  So, it tries to print a string, and will crash if it doesn't find a null character within a certain distance.
> JTRACE: (a.addr) -> ((void *)a.addr); WAS 'char *'

- test/autotest.py
The title says it all: fixing commit 5e05c37
> Fix 5e05c37 format error: autotest.py:printError()

- src/dmtcp_coordinator.cpp
- src/dmtcp_restart.cpp
Fixing several bugs, and some minor fixing of formats/comments in dmtcp_restart.cpp
Without this fix, things like `mana_launch -i5 mpi-proxy-split/test/wave_mpi.mana.exe` were failing to create a checkpoint.
Also, without this fix, the initial default stale timeout of 7 hours wasn't taking effect.
The original PR $1064 was pushed in on Sunday, Sept. 17, creating these bugs.
> Fix "stale timeout" (commit 0f58657 from PR #1064)

- src/dmtcprestartinternal.cpp
@karya0,
&nbsp;&nbsp;&nbsp;&nbsp;Since you're re-doing dmtcp_restart, I would prefer if you can review this bug fix.  But if you're not available, then @xuyao0127 can review it.  Apparently, `make check-presuspend` was failing since 2017, but if the test machine didn't have localhost, then we were not testing this.
* This fixes 'make check-presuspend'.
* In commit 8085468c, if dmtcp_restart did not specify --join or --new, then COORD_ANY was used.  But if a preexisting DMTCP coordinator was available, then --join would be used instead of --new.  Commit 8085468c fixed that.
* But if dmtcp_restart was used with multiple checkpoint images, then --new was used for each of the ckpt images.  So, the second ckpt image would fail.  So, this commit changes COORD_NEW back to COORD_ANY on the 2nd …
> Bug fix 8085468c: COORD_NEW->COORD_ANY on 2nd ckpt img

- src/mtcp/mtcp_util.c
This bug was found by @karya0 .  I'm submitting it now so as not to delay.  But the original bug was mine, and @karya0 discovered thsi bug.
> mmap_fixed_noreplace: Fix preprocessor '#define'

- jalib/jalloc.h
* Bug fix for commit e64459ccf
* If JALIB_ALLOCATOR is not defined, it fails to compile.  We move `getAllocArenas` outside of the conditionalizatio
> jalloc.h: getAllocArenas: JALIB_ALLOCATOR always

- test/syscall-tester.c
* In BasicState, it did: fd=open(file); close(fd) and unlink(file) When checkpointing between close() and unlink(), resume would still unlink 'file'.  And then restart fails to do 'unlink(file)'
* See comment in syscall-tester.c about TODO: // TODO:  DMTCP should offer:  `dmtcp_precious_file(file)`
//        At checkpoint time, even if the fd is closed, if the
//        file still exists on disk, then pretend that
//          ./dmtcp_launch --checkpoint-open-files ...
//        was used, but only for this file.
This bug is causing DMTCP to fail its status check on github.  Let's review this quickly, so as to get the testing on github working again.
> Fix syscall-tester.c; Remove BasicStat test

- src/dmtcprestartinternal.cpp
- src/plugin/pid/sched_wrappers.cpp
- src/rwlock.cpp
- src/signalwrappers.cpp
- test/autotest.py
- test/pthread1.c
- test/vfork1.c
The github commits say it all (with oldest commits first):
* Clean up autotest for syscall-tester
* Fix some compiler warnings; Polish autotest.py
* plugin-example-db test never did as intended
* Fix vfork[12] tests: They had a bug from the start
* Lower timeout for pthread[345] tests
(Empirically, the continuous integration seems to succeed more often with this.)
> Fix compiler warnings; bug fix for vfork1, problem w/ plugin-example-db

- util/gdb-dmtcp-utils.py
Two commits for util/gdb-dmtcp-utils
1. load-symbols-library now handles addresses or filenames of executable file, not just for library files.
2. load-symbols-library now handles a default with no arguments:
With no arguments, it will now load symbols from the newest call frame that does not yet have loaded symbols (that does not yet show a function name).
> Improve gdb dmtcp utils

- configure
- configure.ac
- src/threadlist.cpp
- test/pthread1.c
On CentOS 7 (glibc-2.17),, this would not even compile.  This fixes it.  It's trivial to review.
> Fix pthread1 for compiling

- configure
- configure.ac
- include/config.h.in
- include/procmapsarea.h
- src/mtcp/mtcp_check_vdso.c
- src/mtcp/mtcp_restart.c
- src/util_exec.cpp
- src/util_misc.cpp
- test/autotest.py
- test/dmtcp5.c
- test/syscall-tester.c
There are two general bugs, that happen to be uncovered when porting to Debian-12 on ARM64.  This PR has been tested on a Raspberry Pi on ARM64/Debian-12, and all tests pass now.
**BUG #1 (first commit):**
Debian-12 (bookworm) on ARM64 has a page size of 16384, instead of the traditional 4096.
This PR calculates MTCP_PAGE_SIZE in configure.ac using `sysconf(_SC_PAGESIZE)`, and then defines it in `config.h`.  We no longer do a separate `#define MTCP_PAGE_SIZE` in files outside of `config.h`.
**BUG #2 (second commit):**
`man 2 readlink` says that it doesn't NUL-terminate strings in the buffer that it writes.  This was happening on ARM64 when calling readlink on `/proc/self/exe`.  That caused a bug on restart.  This now fixes it.
> configure.ac: define MTCP_PAGE_SIZE in config.h; zero out buf before calling readlink()

- util/cpplint.py
- util/dmtcp-style.py
This updates the `util/dmtcp-style.py` and `util/cpplint scripts.py` in util from python2 to python3.
Prior to this, any 'git commit' for a C++ file would not work, and we had to use `--no-verify`.  For dmtcp-style.py, the fix was a trivial change:  decoding a bytes object into a string.  For cpplint.py, I accepted the automated fix:
>   `2to3 -f all -f idioms -w util/cpplint.py`
**@karya0 ,**
*If this is good enough, then I will wait for an "approve" and push it in.  If you'd like to first get more recent Google scripts, let me know soon.  The current Google style scripts are from 2009.*
> Update Google style scripts for git commit for dmtcp style

- src/mtcp/mtcp_restart.c
- src/processinfo.cpp
- src/writeckpt.cpp
mtcp_restart.c: If restoreBuf overlaps, try two more restoreBuf regions of the same size.
* In Linux 6.1 (Fedora-38), for mtcp_restart (compiled with '-fPIC'), we see
that vvar/vdso are below stack; stack starts near 0x4000000000  For example:
>    0x3ff7ffc000       0x3ff7ffe000     0x2000        0x0  r--p   [vvar]
>   0x3ff7ffe000       0x3ff8000000     0x2000        0x0  r-xp   [vdso]
>   0x3ffffdf000       0x4000000000    0x21000        0x0  rw-p   [stack]
With address space randomization, the restoreBuf has a high probability
of overlapping with vvar/vdso.  So, we use 3 contiguous restoreBuf regions.
At least one of them has no overlap if region < RESTORE_TOTAL_SIZE.
> Fix restoreBuf overlaps

- configure
- configure.ac
- include/config.h.in
- jalib/jalloc.cpp
* FIXME:  We should use futex_wait, futex_post instead of pthread_mutex_lock/unlock for ARM64 for the reasons below. Add another commit.
* See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70814 for the problem with /lib/aarch64-linux-gnu/libatomic.so.1 on ARM64 as of Sept., 2024.  (tested on libc-2.36)
@maxwellpirtle, Does this PR now fix the bug you saw with McMini during startup?
@karya0 ,
This was a weird bug.  jalloc.cpp had HAS_ATOMIC defined, and used the C++ atomics. That caused C++ to delegate to libatomic.so.  But in libatomic.so, they did _not_ use the atomic assembly instruction.  Instead, they called `pthread_mutex_lock`.  Unfortunately, McMini had its own wrapper around  `pthread_mutex_lock`.  And that led to DMTCP getting control again and DMTCP trying to do an atomic in …
> We cannot trust ARM64 for HAS_ATOMIC

- src/plugin/pid/glibc_pthread.h
- util/check-pthread-tid-offset.c
This updates to confirm the constant for RISC-V now.
`util/check-pthread-tid-offset -v` now has a clearer message.
As before, ./configure runs this utility to verify that the tid offset has not changed in the most recent glibc.
> util/check-pthread-tid-offset.c: update for risc-v

- test/autotest.py
This is trivial to review.
1.  In Python, an `int / int` returns a float.  We wanted to return an int.  Hence, `int // int`
2. If `autotest.py --verbose` and `JWARNING` or `JASSERT` occurs, then it starts printing in color, and the timeout in autotest kills the process.  Now, autotest.py will clear the color mode at the next test.  (And of course, the user can call `reset` if it was only a single test for `autotest`.
> autotest.py: int/int (float); --verbose/JWARN sets color mode

- src/dmtcp_command.cpp
- src/dmtcp_coordinator.cpp
This was checkpointing, but not also killing the computation, which `-kc` was supposed to do.
This is fixed now.  This should be trivial to review.  The bug fix is just 3 lines (in the first commit).  (The second commit is to clean up some code in `dmtcp_command.cpp`.  But also simple.)
And this has been a long-standing bug, ever since we chose to internally use the unique command 'K' instead of '-kc', for reasons of simplifying the `coordinatorapi.cpp` logic with a single character.
And of course, we need this fix, also, before the DMTCP-3.1.0 release.  :-(
> Fix 'dmtcp_command -kc'

- src/dmtcp_coordinator.cpp
On a RISC-V machine, `dmtcp_launch -i5 ...` was failing to checkpoint.  Presumably, it was because the machine had a slow filesystem and network.
In order to debug, it was necessary to simplify the code.  It was tested with `dmtcp_launch -iXX ...`, `dmtcp_command -kc`, `dmtcp_command -c`, a`dmtcp_restart -iXX ...`, and a few other combinations.
The simplification gatthered together all timeout rand interval routines (whatever would affect `alarm()`.
This include `timerExpired`, `timeout`, `staleTimeout`, `theCheckpointInterval`, `theDefaultCheckpointInterval`, etc.
It was important to continue to support `staleTimeout'.  Too often, multiple users would use the same host, and one user would forget to kill his or her coordinator.  So, everyone else then had to remember not to use the …
> dmtcp_coordinator:  Simplify and fix timeout logic

- configure
- configure.ac
- jalib/jalloc.cpp
- plugin/Makefile.in
- src/Makefile.am
- src/Makefile.in
- src/dmtcp_command.cpp
- src/dmtcp_coordinator.cpp
- src/dmtcp_launch.cpp
- src/dmtcpworker.cpp
- src/execwrappers.cpp
- src/plugin/Makefile.in
- src/procselfmaps.cpp
- src/shareddata.cpp
- src/tls.cpp
- test/autotest.py
- util/gdb-dmtcp-utils.py
First commit:  Change configure.ac, src/Makefile.am to recognize if this is aarch64 with gcc/g++.  If so, then due to what is arguably a bug, dwcas in jalloc.cpp fails for `__sync_bool_cmpare_and_swap`.  The comments tell the full story.
In the second commit, we have a problem, because the tiny dmtcp_command executable has to support all of the complexity of libjalib.a.  In particular, dmtcp_launch/restart/coordnator was fixed by the first commit.  But for dmtcp_command, it uses jalloc (even though there's no good reason for that).  In the future, we should simply remove JALLOC and jalloc.cpp:malloc from being called by dmtcp_command.cpp/coordinatorapi.cpp.
The third commit is simply a spell fix and fixing minor typos.
> Aarch64 jalloc fixed

- src/dmtcp_coordinator.cpp
Fixes a bug in which `dmtcp_launch -p XX ...` would create a coordinator, but `ps` and `ps uxw` would show the default port (7779).  This also fixes a small bug where `ps` would cut off the last digit.
(But `ps` may only show processes in short form from the current session, and not from other windows or for other users.  However, `pstree` probably show other users in short form.)
> dmtcp_coordinator -pXX: ps uxw now shows port XX

- jalib/jassert.cpp
- jalib/jassert.h
- src/plugin/dl/dlwrappers.cpp
- src/plugin/ipc/socket/connectionrewirer.cpp
- src/plugin/ipc/ssh/dmtcp_sshd.cpp
- src/plugin/pid/glibc_pthread.h
- src/plugin/pid/sched_wrappers.cpp
- src/processinfo.cpp
- src/writeckpt.cpp
- util/gdb-dmtcp-utils.py
Four small, unrelated commits; easy to review:  Let's reiew this before the 3.1.0 release.
1. JWWARNING/JNOTE not handling EscapeChar (color)  (JWarning was setting color to yellow permanently, and JNOTE did not print in green, although I assume that was the intention)
2. pthread_getschedparam wrapper: bug in failure case (original commit, June, 2023; Added a FIXME comment to remind us to fix it)
3. Fix typos and obsolete TODO comment
4. gdb-dmtcp-utils.py: polishing; no functional diff
> Misc before 3.1.0

- jalib/jalloc.cpp
In `jalib/jalloc.cpp`, dwcas uses 128-bit (16-byte) data structures.  We need to align them on a 16-byte boundary for lvlXStorageBuffer[].   The compiler can align uint128_t datatypes, but in this case, gcc doesn't apparently know that the class instance contains 128-bit quantities.
This was exposed for ARM64, when the commit 121166 was added (Added Coordinator Plugins).
So, we add an `aligned` attribute.
> Align jalloc.cpp:lvlXStorageBuffer[] to 16 bytes

- include/procmapsarea.h
- src/dmtcp_launch.cpp
- src/writeckpt.cpp
These two commits are required by MANA. 
1. Commit 121fe4eda91c01efa5a766a49939c1b14a4b11b3 allows dmtcp_launch to defer initializing libdmtcp.so if the "--mpi" flag is used. This change is minimal compared to introducing a new API in dmtcp_launch.
2. Commit 121fe4eda91c01efa5a766a49939c1b14a4b11b3 changes the interface of dmtcp_skip_memory_region to allow plugins to save part of the examined memory segment, and check the remaining segment in the next iteration. This is required for split-process plugins in case the kernel combines memory segments in the upper and lower half into a single segment.
> Features for mana

- src/dmtcprestartinternal.cpp
The src/dmtcprestartinternal.cpp was a duplicate of mtcp_restart.cpp
for MANA, but it was not updated. This change only affects MANA.
> Set WorkerState to RESTARTING in src/dmtcprestartinternal.cpp

- README.md
It's been much too long since we revised the README.md page of DMTCP.  If you want to see the displayed markdown, then go to README.md below, click on the hamburger menu, and select "View file".
> Revise outdated DMTCP page (and point to MANA)

- src/util_misc.cpp
- test/autotest.py
- util/dmtcp-style.py
1. Fix compiler warnings, due to new `ASSERT_EQ(lhs, rhs)`
lhs and rhs must be of same type; snprintf fixed to have larger buffer
2. util/dmtcp-style.py: Fix 02a5d6e55b4 (bad regex)  ( '\.'->'[.]' ; '\/'->'/' )
3. autotest.py(emacs): emacs-nox can also fork a child process.
USE:  runtest("emacs", [1, 2], ...)    [ emacs forks a temporary child process during initialization ]
(We had `runtest("emacs", 1, ...)` before.)
> Minor fixes

- include/util.h
- src/dmtcprestartinternal.cpp
- src/shareddata.cpp
- src/util_misc.cpp
1. Setting the worker state to RESTARTING in the `RestoreTarget::initialize()` function. MANA uses `lower-half` to restore the upper half memory on restart. The `lower-half` program calls `RestoreTarget::initialize` directly, instead of the `DmtcpRestart::processCkptImages()` function.
2. Add `MAP_FIXED` flag when allocating the shared area during restart. This avoids potential conflicts between the shared area and other memory segments, the restore buffer for example. I used `MAP_FIXED` instead of `MAP_FIXED_NOREPLACE` because in some senerios, the shared area has already been allocated. Using `MAP_FIXED_NOREPLACE` will fail in such cases. We can ignore the failed mmap, but it will be the same as using `MAP_FIXED`
> Adding changes that allows MANA to use the standard DMTCP

- src/writeckpt.cpp
This commit fixes a bug when writing memory areas to disk. Previously, nscd areas are written to the disk before calling the `dmtcp_skip_memory_region_ckpting()` functions. Therefore, no matter if a plugin decides to skip the nscd area, the nscd area will always be written to the disk.
> Check if plugins need to skip nscd regions

- src/threadlist.cpp
- src/threadlist.h
When using JALLOC_MALLOC for motherofall allocation, we can get into infinite recursion if a user application has put wrappers around mmap. The fix is to use a static buffer.
> Use static buffer for motherofall.

- include/util.h
- src/shareddata.cpp
- src/util_misc.cpp
Util::mmap_fixed_noreplace emulates the mmap() with MAP_FIXED_NOREPLACE
flag for old systems. It uses a regular mmap() with the given address
and check if the return value is the same as the given address. However,
we found a case that the kernel returns a different address although the
requirest memory range is available. Therefore, the mmap_fixed_noreplace
function returns an error message EEXIST, which is not expectec.
Now we check if the requested memory range is available by calling mlock()
page by page. The mlock function will return -1 with an errono of ENOMEM.
If there's no already mapped pages in the request memory range, the function
will call mmap() with MAP_FIXED. Otherwise, the function will return
MAP_FAILED with an errno of EEXIST.
> Fixed a bug in Util::mmap_fixed_noreplace

- src/dmtcp_coordinator.cpp
> Coordinator: Fixed interval checkpointing.

- include/shareddata.h
- src/plugin/svipc/sysvipc.cpp
- src/plugin/svipc/sysvipcwrappers.cpp
- src/shareddata.cpp
- test/sysv-shm1.c
- test/sysv-shm2.c
IPC_PRIVATE can [now] be called multiple times and it will in turn create new handlers every time.
Also updated sysv-shm1 test to create shm segments with IPC_PRIVATE key.
Thanks @gkliu for reporting the bug and creating an initial PR (#1191) with the fix.
> Fixed IPC_PRIVATE handling for SysV Shm.

- src/dmtcpworker.cpp
- src/plugin/pid/glibc_pthread.cpp
- src/plugin/pid/pid.cpp
- src/plugin/pid/pid_miscwrappers.cpp
- src/plugin/pid/pidwrappers.cpp
- src/plugin/pid/virtualpidtable.cpp
- src/plugin/pid/virtualpidtable.h
Using getpid() in VirtPidTbl initialization causes recursion in certain cases where a foreign constructor may be called before DMTCP's initializer kicks in.
> Fix VirtPidTbl initialization to not rely on getpid.

- src/miscwrappers.cpp
- src/syscallsreal.c
- src/syscallwrappers.h
- src/wrappers.cpp
- test/syscall-tester.c
This is a new system call introduced in Linux 5.9. The added test fails without the wrapper and passes with wrapper.
> Added close_range test to syscall-tester.

- include/wrapperlock.h
- src/plugin/pid/virtualpidtable.cpp
- src/shareddata.cpp
- src/wrapperlock.cpp
These commits fix issues that are observed during initialization when non-glibc malloc libraries and programs where constructors are called before DMTCP is fully initialized.
> Several initialization bugfixes

- src/miscwrappers.cpp
- test/syscall-tester.c
Check kernel and glibc version when defining wrappers and tests for the `close_range()` syscall. According to the man page, `close_range()` requires `kernel >=5.9` and `glibc >=2.34.`
> Check kernel & glibc ver. for close_range syscall
